### ISSUE TITLE
Add documentation to Libvirt VMs disks cache support #1003

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1038]
As part of #1003  we need to add documentation for features added in #1003

**Comment by samvarankashyap** [comment]
@mcornea ^^^

**Comment by mcornea** [comment]
@samvarankashyap Where should I add the documentation for the feature? I've already added an example of the options in docs/source/examples/workspaces/libvirt/PinFile.

**Comment by samvarankashyap** [comment]
@mcornea nvm I added the parameter as part of #1075
