### ISSUE TITLE
Linchpin destroy --tx-id broken since v1.7.0 release

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#1066]
**Describe the bug**
If you enable rundb in your linchpin conf, run linchpin up, then try to destroy that transaction using
```
linchpin destroy --tx-id 1
```
You get:
```
Section '{'run_id': 1, 'topology': {u'topology_name': u'beaker-slave', u'resource_groups': [{u'resource_group_name': u'beaker-slaves', u'resource_definitions': [{u'job_group': u'multiarch-qe', u'whiteboard': u'Dynamically provisioned', u'role': u'bkr_server', u'recipesets': [{u'count': 1, u'variant': u'Server', u'arch': u'x86_64', u'name': u'null', u'distro': u'RHEL-ALT-7.5'}]}], u'resource_group_type': u'beaker'}]}}' not a valid top-level PinFile section. valid sections are '['topology', 'layout', 'cfgs', 'hooks']'
```

**To Reproduce**
0. Install any linchpin >= 1.7.x
1. Set `use_rundb_for_actions = True` in your linchpin file
2. Run `linchpin up` with the dummy PinFile
3. Get the transaction id from the run log, linchpin.latest, or linchpin journal
4. Use `linchpin destroy --tx-id $transaction_id` (where $transaction_id is the transaction id that you looked up).
5. Weep :(

**Expected behavior**
I expected the hosts brought up through that transaction to be destroyed, as they were in <= 1.6.5 since the release of the --tx-id feature.

**Edit**
Fixed linchpin.conf  variable name.

**Comment by 14rcole** [comment]
@jaypoulz Is `use_rundb_for_transaction` in linchpin.conf?

**Comment by jaypoulz** [comment]
@14rcole oops, I meant `use_rundb_for_actions` but yes, under the [lp] section.
