### ISSUE TITLE
RFE: Openstack quota check prehook

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1070]
Sub-case of #871 - pre-hook that will check Openstack quota before every action (server, network, storage, etc) and will decide if there is enough resources to try some of the provisioning. This could be achieved with [os_quota](https://docs.ansible.com/ansible/latest/modules/os_quota_module.html) module.

**Comment by samvarankashyap** [comment]
Needs design and implementation. 
Ready to go ticket for next sprit based ansible module is given. 
However, the difficulty might arise when we need to write a module in linchpin that parses the Pinfile and determine the number of instances for each topology for a quota check.

**Comment by 14rcole** [comment]
Closing due to time constraints as we move into maintenance mode
