### ISSUE TITLE
RFE: Template based Pinfile creation for OpenStack

### ISSUE THREAD

**Issue by skatlapa** [CentOS-PaaS-SIG/linchpin#1086]
This is a subset of https://github.com/CentOS-PaaS-SIG/linchpin/issues/1058
 
The aim here is to maintain a set of jinja templates having default values  to be populated in the workspace so that user would only have to do minimal changes and need not worry about the format. The idea is to be able to make the overrides from cli. 

The values will be based off of the JSON schemas from each of the providers.

**Comment by samvarankashyap** [comment]
Moving to the backlog. shall be revisited again
