### ISSUE TITLE
RFE: Collect VMware boot logs

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1104]
Subcase of #868 to collect VMware vm boot logs that are stored in `vmware.log` inside  the datacenter, for example: `https://192.168.122.125/folder/vmware-node/vmware.log?dcPath=ha-datacenter&dsName=ha-datacenter&VMware-CSRF-Token=04x6cckqkba6fzsfr4js00fmx2mcf7os`
There is a [vsphere_copy](https://github.com/ansible/ansible/blob/60d134aeaf0feb963e5d35c67fc396d461c528bb/lib/ansible/modules/cloud/vmware/vsphere_copy.py) module to copy files to a datacenter but it need to be extended to support  fetching.

**Comment by 14rcole** [comment]
Closing due to time constraints as we move into maintenance mode
