### ISSUE TITLE
(8) Create libvirt authn/authz components (possibly via cloud-init) for nodes when provisioned

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#111]
Provide key-based authn/authz
Provide linchpin user (or override option with password)
Provide host key retention for existing nodes

https://trello.com/c/GdtglbHH/135-ci-provisioning-linch-pin-create-libvirt-authn-authz-components-possibly-via-cloud-init-for-nodes-when-provisioned

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cloud-Init Functionality](https://trello.com/c/duaJgitw/13-cloud-init-functionality)

**Comment by herlo** [comment]
@samvarankashyap is planning on discussing this with a libguestfs expert in Brno in the next week or so. Hopefully, this can make authentication easier.

**Comment by samvarankashyap** [comment]
Ready with libvirt install scripts
Need to work on the docs
Waiting for rundb integration to happen.

**Comment by herlo** [comment]
Fixed by #383
