### ISSUE TITLE
RFE: Linchpin AppImage (Preview)

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1114]
Linchpin distribution is currently done only with pip and containers. Both options are not simple and require knowledge and experience. AppImage is a single binary that contains all the required files to run a program, the only downside is it requires installing fuse on the system host (available on most distrobutions) and the file size. However it could be a good alternative in some cases such as getting started.

**Comment by samvarankashyap** [comment]
Blocked on getting permissions to ci-env

**Comment by probonopd** [comment]
Can the AppImage be downloaded somewhere for testing?

**Comment by abraverm** [comment]
@probonopd it was supposed to be part of the release but there was some unknown problem with the job and the @samvarankashyap  disabled it. You can track progress in issue #1735.
