### ISSUE TITLE
update API documentation and add examples

### ISSUE THREAD

**Issue by vasukulkarni** [CentOS-PaaS-SIG/linchpin#1116]
Please update the API documentation for create/delete/destroy and maybe some examples too that will make it easy to use in the library.

**Comment by samvarankashyap** [comment]
@vasukulkarni 
Thank you for reporting issue. 
Currently, linchpin API is undergoing restructuring to simplify the end user usage. 
We will make sure to include, and update the documentation w.r.to it.

**Comment by samvarankashyap** [comment]
#1169 fixes this issue
