### ISSUE TITLE
RFE: Beaker provider support for distro_virt key in the topology schema

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1140]
We have some users that have some use cases where they want to reserve a virt capable machine or VMs that Beaker is managing as part of their test environments. 

The best way they've configured their Beaker Job XML to consistently be able to reserve these types of systems is by being able to set the distro_virt tag. 
```
'distro_virt', '=', ""

```
Currently there is no option or way to supply this tag in the Linchpin Beaker topology. We should enable this key like, distrorequires, and it takes the same input format as hostrequires.
```
distrorequires:
    - tag: distro_virt
      op: "="
      value: ""
```

**Comment by samvarankashyap** [comment]
@p3ck quick question:  Would enabling distrorequires key in schema 
be sufficient for the fixing the issue or do we have to change logic in beaker module ?

**Comment by p3ck** [comment]
```
'distro_virt': XmlDistroVirt, #deprecated

class XmlDistroVirt(ElementWrapper):
    """
    This is a noop, since we don't have virt distros anymore.
    """
    pass
```

It doesn't do anything..  maybe placebo affect?

**Comment by samvarankashyap** [comment]
@Dannyb48 any comments ?

**Comment by Dannyb48** [comment]
Interesting. Let me double check. 
@p3ck just curious is that code snippet from the beaker-client code?

**Comment by p3ck** [comment]
@Dannyb48 Nope - that is from the server side where it actually processes the xml nodes and attributes.
https://git.beaker-project.org/cgit/beaker/tree/Server/bkr/server/needpropertyxml.py#n343

**Comment by Dannyb48** [comment]
Ok, I will do some quick testing see if I am seeing a placebo affect. 

They still refer to it in there job xml docs.

https://beaker-project.org/docs/user-guide/job-xml.html

**Comment by p3ck** [comment]
https://gerrit.beaker-project.org/#/c/beaker/+/6585/

**Comment by samvarankashyap** [comment]
closing in favor of previous comments 
@Dannyb48 feel free to re-open if needed

**Comment by Dannyb48** [comment]
no worries, thanks for the help guys!
