### ISSUE TITLE
RFE: Add credential management to new linchpin API

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1171]
we don't have to block this change, is an option to pass credentials with the API:
```
wrks.credentials = linchpin.api.credentials.openstack(name='psi', auth_url=...)
```
Maybe something simpler like:
```
creds = """
[psi]
auth_url = ...
"""
wksp.load_credentials(creds)
```

currently, we do have a helper function to set credential_path

wksp.set_credential_path() 
function to help users to point out to the credential space.
Given, multiple formats of credentials for each cloud provider. I believe it would take time implementing and testing them.

**Comment by 14rcole** [comment]
@samvarankashyap do you think this can be completed in the next month or two?  Or should we close it?
