### ISSUE TITLE
Inventory ordering and grouping fails in python3.7

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1177]
**Describe the bug**
Inventory ordering and grouping fails in python3.7

**To Reproduce**
- create a fedora30 container
- install python3.7 in fedora30 container
- install linchpin 
### run unit tests from the repository 
- run python setup.py test 
**Expected behavior**
unit tests should pass 

**Additional context**
This bug was discovered in recent travis-ci testing of python 3.7 
refer units test runs of PR #1174 for more details

**Comment by 14rcole** [comment]
@samvarankashyap It seems like the inventories are still generate correctly so I think it's safe to say that the bug is in the unit tests and not the inventory generation code.  I'm submitting a PR now

**Comment by samvarankashyap** [comment]
@14rcole please make sure they are backward compatible with python 2.7.x version

**Comment by 14rcole** [comment]
Fixed in #1174
