### ISSUE TITLE
Fix beaker openstack tests

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1183]
The beaker openstack integration test has been disabled for a while.  We either need to fix it so it'll pass or remove it

**Comment by 14rcole** [comment]
I added a bandwidth tag to this, but there's a real possibility that it should be a part of the CI overhault

**Comment by samvarankashyap** [comment]
I believe this ticket is no longer necessary given we moved to mock tests.
Please re-open this issue if it's needed.
