### ISSUE TITLE
Automate AppImage upload to external source on release

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1185]
**Is your feature request related to a problem? Please describe.**
We currrently have app image as a part of #1115 . However it would be great if we could run a step in Jenkins to upload appimage on release. 
Preferrably github releases page.

**Comment by samvarankashyap** [comment]
waiting on credentials @abraverm

**Comment by 14rcole** [comment]
Speaking of packaging systems we claim to support...

**Comment by abraverm** [comment]
I still don't have access to Jenkins...

**Comment by 14rcole** [comment]
@abraverm Have you contacted Brian Stinson?

**Comment by abraverm** [comment]
I tried the IRC(no reply), and there is a ticket in centos, I can try sending him an email...
