### ISSUE TITLE
Linchpin version 1.7.5 not available on pip(https://pypi.org/project/linchpin/ )

### ISSUE THREAD

**Issue by sonam1412** [CentOS-PaaS-SIG/linchpin#1193]

**Comment by samvarankashyap** [comment]
@sonam1412 Linchpin 1.7.6.1 is currently available on PyPI. 
We are investigating into the missing release of linchpin 1.7.5

**Comment by samvarankashyap** [comment]
Merge trigger job on jenkins hung up during the merge. 
Causing linchpin 1.7.5 to be missing 
however, With a short life cycle of linchpin in consideration and also availability of linchpin 1.7.6.2 
We are closing this issue.
