### ISSUE TITLE
Reference\links testing

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1200]
User reported that some links are not working (specifically in AWS  -https://raw.githubusercontent.com/CentOS-PaaS-SIG/linchpin/develop/docs/source/examples/workspaces/topologies/aws-ec2-vpc-net.yml). Validating manually that links are working or depending on users is too risky. I suggest adding a test to documentation using some tool such as:
https://linkchecker.github.io/linkchecker/
https://github.com/stevenvachon/broken-link-checker

**Comment by 14rcole** [comment]
We believe this was completed a while ago
