### ISSUE TITLE
Manage disks related to virtual machine in given vCenter infrastructure

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1205]
https://docs.ansible.com/ansible/latest/modules/vmware_guest_disk_module.html

**Comment by 14rcole** [comment]
It seems like we don't have customers using VMware and we don't have a way of testing VMware features.  I'm going to close this.  If somebody with access to VMware resources would like to implement and test this functionality they are welcome to do so.
