### ISSUE TITLE
Manage a VMware Standard Switch to an ESXi host

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1206]
https://docs.ansible.com/ansible/latest/modules/vmware_vswitch_module.html#vmware-vswitch-module

**Comment by 14rcole** [comment]
It seems like we don't have customers using VMware and we don't have a way of testing VMware features.  I'm going to close this.  If somebody with access to VMware resources would like to implement and test this functionality they are welcome to do so.
