### ISSUE TITLE
Support Azure provider

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1212]
https://docs.ansible.com/ansible/latest/modules/azure_rm_virtualmachine_module.html#azure-rm-virtualmachine-module

Create, update, stop and start a virtual machine.

**Comment by 14rcole** [comment]
I personally think it's a good idea to target this for 2.0, but do we have access to Azure resources on which we can run integration tests?

**Comment by abraverm** [comment]
Like we said in the meeting, lets put it in the "preview" state and target for 2.0 as supported feature. I'm working right now on getting an account for development and testing.

**Comment by samvarankashyap** [comment]
closing ticket since its already implemented
