### ISSUE TITLE
Support Alibaba cloud

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1222]
Create, start, stop, restart, modify or terminate ecs instances.
Add or remove ecs instances to/from security group.

https://docs.ansible.com/ansible/latest/modules/ali_instance_module.html#ali-instance-module

**Comment by 14rcole** [comment]
This is something that can be done by creating an Ansible Galaxy role and providing the role in the resource groups

https://linchpin.readthedocs.io/en/latest/developing_roles.html
