### ISSUE TITLE
Linchpin doesn't return correct ip when use count>1 and multi-network

### ISSUE THREAD

**Issue by JunqiZhang0** [CentOS-PaaS-SIG/linchpin#1241]
When you have count = 2, and assign two networks.
Result: I got Just 2 IPs returned
Expected Result: Should return 2*2 = 4 IPs

**Comment by Dannyb48** [comment]
As part of this change, can we also differentiate between which IP is 'public' and which is 'private' like the other providers (OpenStack/AWS). I think this might have to be built into the libvirt playbooks

In libvirt a private network is one without the **forward** element[1] in the network. 

Maybe add another task that queries the networks and checks for this element. Then save a temp variable that contains a map which notes which is private and public. Which can be used later When building the IP address list for each VM/instance  

[1] https://libvirt.org/formatnetwork.html#examplesPrivate

**Comment by JunqiZhang0** [comment]
> As part of this change, can we also differentiate between which IP is 'public' and which is 'private' like the other providers (OpenStack/AWS). I think this might have to be built into the libvirt playbooks
> 
> In libvirt a private network is one without the **forward** element[1] in the network.
> 
> Maybe add another task that queries the networks and checks for this element. Then save a temp variable that contains a map which notes which is private and public. Which can be used later When building the IP address list for each VM/instance
> 
> [1] https://libvirt.org/formatnetwork.html#examplesPrivate

**Comment by JunqiZhang0** [comment]
@Dannyb48 Yes, shouldn't very complex
