### ISSUE TITLE
Create videos that showcase LinchPin's core functionality

### ISSUE THREAD

**Issue by maneeshmehra** [CentOS-PaaS-SIG/linchpin#1246]
As part of making the user experience better, we should have short (no more than 5 min) videos that showcase some core functionality of LinchPin. Here are couple of ideas of what these videos could cover:

1. Types of linchpin terminology, and workflow 
2. Different types of linchpin pin files
3. LinchPin hooks and how to write a hook 
4. LinchPin command line basic operations
5. LinchPin fetch
6. LinchPin journal
7. LinchPin credential setup for OpenStack
8. LinchPin credential setup for AWS
9. LinchPin credential setup for GCE
10. LinchPin credential setup for Beaker
11. LinchPin provisioning in OpenStack
12. LinchPin provisioning in AWS
13. LinchPin provisioning in Libvirt
14. LinchPin provisioning in Beaker
15. LinchPin provisioning in GCE
16. Linchpin Provisioning on Azure

**Describe the solution you'd like**
These videos should be uploaded to a public forum such as YouTube and linked to LinchPin's documentation at https://linchpin.readthedocs.io/en/develop/getting_started.html

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by samvarankashyap** [comment]
Re-work on documentation. Create a new issue on it. 
Add a task to verify/validate the documentation for linchpin.

**Comment by samvarankashyap** [comment]
Ref : https://github.com/CentOS-PaaS-SIG/linchpin/wiki/Linchpin-Asciinema-Casts 
Except libvirt and azure tutorials are posted above
