### ISSUE TITLE
Gather linchpin consumer metrics and details

### ISSUE THREAD

**Issue by maneeshmehra** [CentOS-PaaS-SIG/linchpin#1253]
**Is your feature request related to a problem? Please describe.**
Gather consumer data on LinchPin (some broad numbers in terms of biggest consumers, what providers do they use for provisioning, how many pin-files, how many topologies per pin files, how many layouts, how many resources are provisioned/de-provisioned per month, typical use cases they use LinchPin for (UI testing, function testing, production deployments etc ?)

**Describe the solution you'd like**
An up2date description of who the consumers of LP are, what are the common use cases, how many times such use cases are executed etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by samvarankashyap** [comment]
closing this issue since it is no longer required. 
Shall be re-opened if necessary.
