### ISSUE TITLE
destroy should be done in reversed order

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1256]
When topology consists of multiple resources that depend on each other and provisioned in a specific order, then Linchpin will fail to destroy as it repeats the provisioning order. Linchpin should destroy resources in a reversed order to handle such case.

**Comment by samvarankashyap** [comment]
@abraverm is it specific to the provider ? 
afaik, the playbooks are structured in such a way that the dependencies are being removed first.

**Comment by abraverm** [comment]
you are right, thank you.
