### ISSUE TITLE
Provisioning AWS keys dumps them to /tmp

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1261]
**Describe the bug**

Doing some testing provisioning AWS resources and noticed that the keys were placed in /tmp.  

`2019-08-07 15:03:02,582 INFO [carbon.provisioners.linchpin_wrapper.write:60] 
TASK [aws : Generate keyfile] *************************************************************************************************************************************************************************************
2019-08-07 15:03:03,054 INFO [carbon.provisioners.linchpin_wrapper.write:60] changed: [localhost] => {"changed": true, "checksum": "c2d9ead8ae7c1eea4b946167d847393a810cd683", "dest": "/tmp/db2_aws_key_pair.pem", "gid": 1000, "group": "dbaez", "md5sum": "75a38c307b6a2ebf421d73149998f3e1", "mode": "0664", "owner": "dbaez", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 1674, "src": "/home/dbaez/.ansible/tmp/ansible-tmp-1565204582.61-228054032924572/source", "state": "file", "uid": 1000}`

This seems to relate to issue #704 where it is using a **keystore_path** variable. The openstack playbooks were fixed to use the **default_ssh_key_path** variable but not the AWS one. 

**To Reproduce**
1. Create a simple pinfile with the following
```aws-ec2-key-new:
  topology:
    topology_name: aws-ec2-key-new
    resource_groups:
      - resource_group_name: "aws"
        resource_group_type: "aws"
        resource_definitions:
          - name: "ec2_keypair"
            role: "aws_ec2_key"
            region: "{{ region | default('us-east-1') }}"
        {% if credentials is defined %}
        credentials:
          filename: {{ credentials.filename }}
          profile: {{ credentials.profile }}
        {% else %}
        credentials:
          filename: aws.key
          profile: default
        {% endif %}
```

2. run `linchpin up`
3. Look in /tmp for the pem file

**Expected behavior**
A way to control the ssh key output based on the **default_ssh_key_path** 

Also what is the intent of the parameter **public_key_path**? I specified it and it didn't do anything, looking at the playbook it's not even referenced at all?

**Comment by samvarankashyap** [comment]
@Dannyb48 Thank you for pointing it out. 
we used to maintain keystore in earlier versions of linchpin.
However, that has been changed by the default_ssh_path. 
This can be fixed by replacing 

https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/provision/roles/aws/tasks/provision_aws_ec2_key.yml#L15

with
```
dest: "/{{ default_ssh_key_path | default('tmp') }}/{{ res_def['res_name'] | default(res_def['name']) }}.pem" 
```
The public key path should be no longer necessary since we have default_ssh_key_path 
which is passed as extra var from linchpin.conf
https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/linchpin.constants#L36

Its a simple fix :)
