### ISSUE TITLE
Add support for Inventory Template

### ISSUE THREAD

**Issue by spoore1** [CentOS-PaaS-SIG/linchpin#1285]
**Is your feature request related to a problem? Please describe.**

Maintaining a large inventory layout in PinFile is difficult.  Currently, I'm using a basic one and pulling data from that to insert hosts into my own inventory file.  I'd like to skip that step and see some level of support for an inventory template.

**Describe the solution you'd like**
Configure linchpin to point to an inventory template file.  Either using the same json format used today or maybe even the other common ini format a lot of ansible inventories use.

**Describe alternatives you've considered**

Maybe define a parameter for the inventory layout in PinFile to point to a template and/or define which format the file is in?

**Additional context**
Maybe support something like:

  layout:
    inventory_layout:
      inventory_file: inventories/test.inventory
      inventory_template: inventories/template.inventory
      inventory_format: ini

**Comment by samvarankashyap** [comment]
I personally like the idea of passing variables into a jinja template file such that they can be rendered into the inventory file. 
This would ultimately avoid the maintaining logic for inventory_layouts too.

**Comment by 14rcole** [comment]
Closing because we don't think we'll have the bandwidth to handle this RFE before LinchPin goes into mantainence mode.  @spoore1 if you'd like to pick it up yourself you're more than welcome to do so

**Comment by spoore1** [comment]
@14rcole thanks for consideration.    If I get time, I'll look at the code.  

If LinchPin is going into maintenance mode, is something replacing it?

Thanks again
