### ISSUE TITLE
RFE: support provisioning Fedora/RHEL CoreOS in Beaker

### ISSUE THREAD

**Issue by miabbott** [CentOS-PaaS-SIG/linchpin#1306]
**Is your feature request related to a problem? Please describe.**
As a user of Fedora/RHEL CoreOS
I want to be able to provision the OS on bare metal hosts in Beaker
so that I am able to perform additional testing of Fedora/RHEL CoreOS on bare metal hosts.

**Describe the solution you'd like**
Provided the necessary inputs for Fedora/RHEL CoreOS (installer ISO, OS image, Ignition JSON, etc), `linchpin` would handle the uploading + configuration of the Beaker job to provision a bare metal host.

**Describe alternatives you've considered**
AFAIK, there is no reasonable alternative for provisioning Fedora/RHEL CoreOS in Beaker.

**Additional context**

The RHCOS team had some initial discussions with the RHT Beaker team about how to go about provisioning an RHCOS host on a bare metal node in Beaker.  A manual process was arrived at, but it is not ideal and could use improvement.  The notes from @StykMartin for this process are reproduced here:

```
So I used the following setup:
- Kernel in Beaker LC
- initramfs in Beaker LC
- Ignition config hosted in BRQ file server -
http://XXXX.redhat.com/~mastyk/rhcos/test.json
- Installation image hosted in BRQ file server -
http:/XXXX.redhat.com/~mastyk/rhcos/rhcos-410.8.20190516.0-metal-bios.raw.gz
- Used the same machine as before
- Used the following kernel parameters
coreos.inst=yes
coreos.inst.ignition_url=http://XXXX.redhat.com/~mastyk/rhcos/test.json
coreos.inst.image_url=http://XXXX.redhat.com/~mastyk/rhcos/rhcos-410.8.20190516.0-metal-bios.raw.gz
coreos.inst.install_dev=sda ip=dhcp
ks=http://XXXX.redhat.com/kickstart/23482
netbootloader=pxelinux.0 rd.neednet=1
- Submitted job
- When I saw on screen CoreOS installer started I removed PXE files.
Few minutes later (~32 minute left on WD) my machine rebooted into
CoreOS!
```

Additional discussion around using `linchpin` to handle the provisioning of Fedora/RHEL CoreOS on bare metal arose on the RHT ci-infra list after the announcement of the merging of Carbon + Linchpin.  It was suggested to file an RFE to continue discussion of this idea.

There is an outstanding patch to `coreos-installer` that would likely be needed for this enhancement to be feasible - https://github.com/coreos/coreos-installer/pull/25

**Comment by samvarankashyap** [comment]
Adding Centos8 to release

**Comment by StykMartin** [comment]
CentOS8 will be supported in Beaker. At this moment I'm able to import it, but still, metadata are not fully right. Waiting for response from CentOS engineering team.

**Comment by samvarankashyap** [comment]
Linchpin team does not handle the internals of the beaker. 
Please do reach out to the beaker team for the support of this ticket. 
I see from the previous comments the issue might be partially resolved by @StykMartin 
Please do re-open this issue if you feel the ticket is closed for the wrong reasons. 
Thank you.
