### ISSUE TITLE
Move Dummy role to Ansible Galaxy

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1362]
This would require us to set up a linchpin account on Ansible Galaxy, write code so that LinchPin can pull relevant roles from Ansible Galaxy, and move the role to Galaxy

**Comment by samvarankashyap** [comment]
@14rcole Can we consider this as closed? 
I believe it is functional in the current branch.

**Comment by 14rcole** [comment]
No.  The role in Ansible Galaxy doesn't have updated tests and such.  After I add the tests I need to move it back into LinchPin, at which point we can close it

**Comment by samvarankashyap** [comment]
@14rcole will be moving ansible galaxy role back to linchpin for reference.
And make sure it does not break it.
