### ISSUE TITLE
[RFE] Floating IP resource on Openstack provider

### ISSUE THREAD

**Issue by morenod** [CentOS-PaaS-SIG/linchpin#1390]
**Is your feature request related to a problem? Please describe.**
Openstack provider dont have floating ip resource

**Describe the solution you'd like**
A resource to request a floating ip from a pool

**Describe alternatives you've considered**

**Additional context**

**Comment by 14rcole** [comment]
LinchPin supports an `fip_pool` flag, is this what you're looking for?

**Comment by 14rcole** [comment]
@morenod any updates?

**Comment by morenod** [comment]
Not sure, I dont see usage examples on the docs. Can I request a new floating ip without assigning it to a server?

**Comment by samvarankashyap** [comment]
No, Currently we do not have support to create floating IPs however, 
there is a module in ansible that supports that 
https://docs.ansible.com/ansible/latest/modules/os_floating_ip_module.html 
@14rcole 
shall we take this on for 1.9.1?

**Comment by 14rcole** [comment]
I don't see why not
