### ISSUE TITLE
PORT integration tests into python3

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1407]
**Is your feature request related to a problem? Please describe.**
Currently, all the tests run in python2.x 
Move all the integration tests into python3 for stronger support for python3.x 

**Additional context**
python 2.x support is being deprecated from version 1.9.0 
It would help if we move tests to python3 faster. 

Part of #283

**Comment by samvarankashyap** [comment]
@14rcole  Am working on a strategy to run beaker tests separately. 
Let's see if it works.

**Comment by samvarankashyap** [comment]
Update: 
Upstream tests have been ported to python3 
however, Downstream tests are waiting yet to be ported with an exception on the beaker.

Centos 7 distro cannot be supported as of now. Due to the fact that libselinux-python3 package is not available in centos7 on which ansible is highly dependent on making it impossible to port at this moment. 
I have tried multiple ways via virtualenv to make it work but could not find a way without libselinux-python3 package. 
Ticket on centos7 requesting the same. 
[https://bugs.centos.org/view.php?id=16389](https://bugs.centos.org/view.php?id=16389)

**Comment by 14rcole** [comment]
We should update to Centos 8 anyway.  That might resolve the issue

**Comment by samvarankashyap** [comment]
I havent thought about it. 
Good idea @14rcole

**Comment by samvarankashyap** [comment]
#1596 should fix this issue. 
Once the PR #1596 is close this ticket can be safely closed.
