### ISSUE TITLE
(1) Ability to override the res_name on the command line

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/linchpin#144]
Currently whatever the res_name in the topology file is that is always the name you get when you deploy.  This can create collisions if you are doing multiple deployments in the same openstack tenant for instance.

We either need a way to override this or deploy with a unique identifier to avoid this

**Comment by samvarankashyap** [comment]
@arilivigni : res_name act as a unique identifiers for resources for now in all the cloud providers except for amazon ec2. Users have to be concerned about the names before they assign . However, even if there is a collision , ansible does not fail the provisioning it just brings meta data of the machine which is already provisioned in outputs and does not effect the inventory. 
One better way to handle this situation is to have a status DB in SQLite which tracks the instances provisioned by the invocation of linchpin helping the users to know about the changed instances.

**Comment by herlo** [comment]
I believe this may be related to #150

**Comment by herlo** [comment]
We have a feature coming for managing resources with unique identifiers. It's currently not scoped, but I suspect it'll hit before 1.0.0.

**Comment by herlo** [comment]
Let's take some time during sprint 3 and scope this out @samvarankashyap
