### ISSUE TITLE
LinchPin doesn't validate if PinFile's name is not PinFile

### ISSUE THREAD

**Issue by JunqiZhang0** [CentOS-PaaS-SIG/linchpin#1490]
When we don't use the default format PinFile, for example, if we use PinFile.yml, linchpin can't recognize. For linchpin up we can specify the option "-p" to use different formats, but "linchpin validate " doesn't have a similar feature.

**Comment by 14rcole** [comment]
The `-p` option is for LinchPin as a whole, not just up and destroy.  I'm surprised it doesn't work for validation though, this will definitely need to be looked at

**Comment by samvarankashyap** [comment]
@JunqiZhang0 Assigned to this ticket is on PTO. 
This ticket shall be taken up in the next sprint.

**Comment by JunqiZhang0** [comment]
Found the right workflow, the -p should be put in front of 'validate' command, otherwise, it won't work
