### ISSUE TITLE
Carbon hangs when running concurrent linchpin API calls

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1511]
**Describe the bug**
When carbon runs the provision task concurrently and at least two tasks are run, one resource will finish running, but the other process hangs indefinitely. 

I think the issue is because when carbon runs concurrently its spinning up multiple processes through the blaster library and now with the progress bar feature in Linchpin that too is also spinning up at least two new processes from there. It looks like one progress bar process is getting stuck. 

**To Reproduce**
1. install carbon from gerrit develop
2. install linchpin from develop
3. download out e2e-acceptance-tests repo from our CCIT gitlab
4. export the following variables
export OS_NETWORK=<provider network>
export OS_KEYPAIR=<user the ccit or db2-test key> 
export BACKEND=linchpin-wrapper
5. fill in the carbon.cfg openstack credentials 
6. run `carbon run -s scenario_upshift.yml -t provision`

Luckily the current users who are using Linchpin in Carbon are doing so with the following flag in the carbon.cfg to have carbon run the provision task sequentially

```
[task_concurrency]
provision=False
```

**Comment by Dannyb48** [comment]
@abraverm ^^^ If we can't find a true solution, any chance we can make the progress bar stuff toggle-able?

**Comment by 14rcole** [comment]
@Dannyb48 did you verify that the issue isn't rundb-related?

**Comment by samvarankashyap** [comment]
@Dannyb48 sometimes it's because of the openstack instances too. 
could you confirm this ??

**Comment by Dannyb48** [comment]
@samvarankashyap @14rcole yes, it is does not look to be either one of those issues. When I switch carbon to run its provision tasks serially in a single process space, it completes no problem. I can reproduce this locally.

I have a nightly job still hung if you guys want to look at it. 

https://ci-ops-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/carbon/job/Carbon-Linchpin-Nightly/31/

**Comment by Dannyb48** [comment]
I've put out feelers for current users using linchpin as a provisioner for their scenarios. I know of three scenarios that use linchpin and currently have the provision task concurrency set to run sequentially to workaround the rundb conccurency issue, so they shouldn't encounter this particular issue that shouldn't run into this issue.

I've asked Adam to check with the rest of this teams scenarios to see if anyone else is using linchpin provisioner with carbon provision task running concurrently just to make it aware.

I think we might not have to hold up the release to fix this particular issue. We could document in the Carbon Changelog that this is a known issue with the Linchpin Provisioner and that the workaround be that they set the carbon provision task to sequentially. But all the other bugs need to be fixed though.

**Comment by abraverm** [comment]
@Dannyb48 I didn't know carbon is using develop version of Linchpin, but I agree that we should have an option to disable the progress bar and verbose mode is perfect for that case.

**Comment by 14rcole** [comment]
Fixed
