### ISSUE TITLE
Create mock data and action_plugins for all providers for integration tests

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1520]
**Is your feature request related to a problem? Please describe.**
With recent developments, we have found a way to reduce the time by mocking the output of Ansible modules. It is implemented for beaker and openstack. 
we would like to implement it for all the other core providers. 

**Describe the solution you'd like**
Have integration tests ran for following providers with mock data:
- Azure #1531 
- GCP 
- AWS
- Libvirt

**Comment by 14rcole** [comment]
I can take on Libvirt once I finish up my tasks for this sprint

**Comment by samvarankashyap** [comment]
Closing this issue since we have broken down the issue into multiple tickets
