### ISSUE TITLE
Documentation 100% refactor proposal

### ISSUE THREAD

**Issue by JunqiZhang0** [CentOS-PaaS-SIG/linchpin#1532]
As a new linchpin user, it's hard to understand how linchpin works and how to develop linchpin with current Doc, it needs to be refactored. It has to be reviewed by people who are not familiar with linchpin

**Comment by samvarankashyap** [comment]
@JunqiZhang0 Is currently on PTO shall be moved to the next sprint.

**Comment by JunqiZhang0** [comment]
https://docs.google.com/document/d/196j7a3qmrTCY4niBpaL6Km4SggEu1y1o6a0QEX9y7AI/edit
This is the update documentation

**Comment by samvarankashyap** [comment]
break this ticket down @JunqiZhang0

**Comment by JunqiZhang0** [comment]
The ticket is already broken down to several tickets
