### ISSUE TITLE
(2) linchpin should allow for become option to pass to ansible

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#155]
In the current invocation of linchpin, sudo is not an option. This is due to some code in invoke_playbooks.py which disables become. Instead, the option should be provided to linchpin rise to enable sudo. 

It was discussed and agreed that the functionality should follow the form ansible has already provided. See http://docs.ansible.com/ansible/become.html for information on ansible's become functionality.

Thus, the usage may look something like this:
```
linchpin rise --become
```
This would default to become_method=sudo, become_user=root. But this could also be overridden as such:
```
linchpin rise --become --become_user='charlie' --become_method='su'
```

This should also be available as config options, possibly in the PinFile or linchpin_config.yml. Though, that detail has yet to be determined.

**Comment by jaypoulz** [comment]
As mentioned in #375, I discussed with @arilivigni and Jeff Burke that this issue speaks to the more general feature of being able to pass arguments to the ansible playbooks directly.  While this could be a direct flag in the CLI, more value could be exposed by allowing pass through of extra-args.

**Comment by herlo** [comment]
Become is a specific feature in ansible. It's used to elevate permissions from a standard user to the root user, for instance. I don't think this is exactly what you are looking for. Though I do agree that passing in arguments through an --extra_vars might be a good way to go about things.

**Comment by herlo** [comment]
Going to target this feature for 1.5.1 or 1.5.2

**Comment by herlo** [comment]
In #464, it was discovered that Libvirt was limiting the managing of users' rights with regard to where to store images, sudo rights, etc. Adjusting [the become parameters](https://github.com/CentOS-PaaS-SIG/linchpin/pull/464/commits/333abb10276c49bd7ccd567f5c8614b7fe49d555) seems to have addressed this in a way via extra_vars (evars) to make the image location more flexible.

**Comment by samvarankashyap** [comment]
@herlo : Do we still need this issue open ?

**Comment by herlo** [comment]
@samvarankashyap agreed. It can be reopened/recreated if necessary.
