### ISSUE TITLE
Cannot run unit tests

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1566]
**Describe the bug**
Unit tests are failing because the linchpin API does not support the progress monitor

**To Reproduce**
1. Go to the linchpin base dir
2. run `python setup.py test`

**Expected behavior**
Tests pass

**Comment by 14rcole** [comment]
@samvarankashyap This will block the next release

**Comment by samvarankashyap** [comment]
@14rcole I am checking it out

**Comment by samvarankashyap** [comment]
fixed by #1568
