### ISSUE TITLE
Beaker examples don't actually create jobs on beaker

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1574]
**Describe the bug**
Beaker examples clain to have run successfully, but do not provision anything on beaker

**To Reproduce**
1. Log in to beaker (`kinit <username>`)
2. run `linchpin up` from `docs/source/examples/workspaces/beaker`
3. Check your jobs on beaker
4. Job doesn't exist

**Expected behavior**
A job is created

**Additional context**
We switched to a new beaker library for python recently, correct?  Could this be related?

**Comment by samvarankashyap** [comment]
@14rcole I remember @Dannyb48 has tested beaker-client with linchpin before. 
I am almost sure, It is not a problem with the beaker-client. 
@14rcole Are you sure you are using the your creds? By default, beaker picks up from beaker.conf creds if it is present. 
@Dannyb48 Any thoughts?

**Comment by Dannyb48** [comment]
@14rcole is it returning right away? do you see a job url getting generated?

**Comment by Dannyb48** [comment]
As long as `BEAKER_CONF` was exported to point to my client config file `~/.beaker_client/config` the example workspace `beaker-simple` was able to generate a beaker job (although I did have to move that localhost file out of the way). Here is the job url:
https://beaker.engineering.redhat.com/jobs/4026660 

I will admit I did not try with `kinit <username>`

**Comment by 14rcole** [comment]
@Dannyb48 It's returning right away with no job url.  I tried it with `kinit`

**Comment by Dannyb48** [comment]
I keep getting issues trying to reproduce locally on my laptop.  After I do the `kinit <username>` and enter my password, I keep getting errors like the following, I still export BEAKER_CONF to point to my beaker client config but in my beaker config I switch `AUTH_METHOD=krbv` and `KRB_REALM=REDHAT.COM`. 

I'm still running Fedora 28 but using python 3.6.8. I'm going to have to provision something newer and re-test. 

```
The full traceback is:
Traceback (most recent call last):
  File "/home/dbaez/.ansible/tmp/ansible-tmp-1579557555.6041706-150815356945781/AnsiballZ_bkr_distro_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/dbaez/.ansible/tmp/ansible-tmp-1579557555.6041706-150815356945781/AnsiballZ_bkr_distro_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/dbaez/.ansible/tmp/ansible-tmp-1579557555.6041706-150815356945781/AnsiballZ_bkr_distro_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.bkr_distro_facts', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bkr_distro_facts_payload_i_kqhffq/ansible_bkr_distro_facts_payload.zip/ansible/modules/bkr_distro_facts.py", line 45, in <module>
  File "/tmp/ansible_bkr_distro_facts_payload_i_kqhffq/ansible_bkr_distro_facts_payload.zip/ansible/modules/bkr_distro_facts.py", line 36, in main
  File "/tmp/ansible_bkr_distro_facts_payload_i_kqhffq/ansible_bkr_distro_facts_payload.zip/ansible/modules/bkr_distro_facts.py", line 20, in __init__
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/bkr/common/hub.py", line 87, in __init__
    self._login()
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/bkr/common/hub.py", line 114, in _login
    login_method()
  File "/home/dbaez/.virtualenvs/lp-py3/lib/python3.6/site-packages/bkr/common/hub.py", line 187, in _login_krbv
    creds = gssapi.Credentials(name=name, store=store, usage='initiate')
AttributeError: module 'gssapi' has no attribute 'Credentials'
```

**Comment by Dannyb48** [comment]
So the problem with my issue is that I think there is a conflicting gssapi libraries being installed, `beaker-client-27` has a dependency on the `gssapi` package. But linchpin as part of beaker requirements is also installing `python-gssapi`, which is an older package that is no longer recommended. This older package is superseding the proper `gssapi` package hence I'm getting that `AttributeError has no attribute Credentials` error. I had to uninstall both the gssapi packages  and install `gssapi` package for it to load all it's modules properly and I got past the error I was seeing.

1) I did `kinit <username>` and entered my credentials
2) exported BEAKER_CONF to point to my local beaker client config
3) `linchpin -vvvv up`
4) Successful provisioned using kinit 

https://beaker.engineering.redhat.com/jobs/4028184

I'm going to file a separate issue for gssapi package issue.

**Comment by Dannyb48** [comment]
Now that I've confirmed that everything is working using `workspaces/beaker-simple` I re-tried the test using the `workspaces/beaker`. Ran `linchpin -vvvv up beaker-new` and I got the same the issue. It returned right away. I'm investigating, I don't think it has anything to do with the beaker client library. Might be an issue with the parameters given to beaker or on the beaker side. I'm investigating

**Comment by Dannyb48** [comment]
So no matter how many times I try to edit the PinFile with different parameters the output is always the same. It keeps returning the same old job id `3931548`, url `https://beaker.engineering.redhat.com/jobs/3931548`, system `kvm-01-guest10.lab.eng.brq.redhat.com`. It's as if it's `hardcoded` some where, I just can't pinpoint where though. Full json debug below. 

```
changed: [localhost] => (item={'role': 'bkr_server', 'whiteboard': 'Provisioned with linchpin', 'max_attempts': 240, 'attempt_wait_time': 60, 'cancel_message': 'Job cancelled on account of rain', 'recipesets': [{'distro': 'RHEL-7.5', 'arch': 'x86_64', 'count': 1, 'name': 'rhel75', 'variant': 'Server'}]}) => {
    "ansible_loop_var": "res",
    "changed": true,
    "hosts": [
        {
            "arch": "x86_64",
            "distro": "RHEL-7.5",
            "family": "RedHatEnterpriseLinux7",
            "id": "3931548",
            "result": "New",
            "rid": "7642234",
            "status": "New",
            "system": null,
            "variant": "Server"
        }
    ],
    "ids": {
        "3931548": "https://beaker.engineering.redhat.com/jobs/3931548"
    },
    "invocation": {
        "module_args": {
            "attempt_wait_time": 60,
            "cancel_message": "Job cancelled on account of rain",
            "job_group": "",
            "max_attempts": 240,
            "recipesets": [
                {
                    "arch": "x86_64",
                    "count": 1,
                    "distro": "RHEL-7.5",
                    "hostrequires": [
                        {
                            "rawxml": "<key_value key=\"model\" op=\"=\" value=\"KVM\"/>"
                        }
                    ],
                    "name": "rhel75",
                    "variant": "Server"
                }
            ],
            "ssh_keys_path": "~/.config/linchpin",
            "state": "present",
            "whiteboard": "Provisioned with linchpin"
        }
    },
    "provision_params": {
        "attempt_wait_time": 60,
        "cancel_message": "Job cancelled on account of rain",
        "job_group": "",
        "max_attempts": 240,
        "recipesets": [
            {
                "arch": "x86_64",
                "count": 1,
                "distro": "RHEL-7.5",
                "hostrequires": [
                    {
                        "rawxml": "<key_value key=\"model\" op=\"=\" value=\"KVM\"/>"
                    }
                ],
                "name": "rhel75",
                "variant": "Server"
            }
        ],
        "ssh_keys_path": "~/.config/linchpin",
        "state": "present",
        "whiteboard": "Provisioned with linchpin"
    },
    "res": {
        "attempt_wait_time": 60,
        "cancel_message": "Job cancelled on account of rain",
        "max_attempts": 240,
        "recipesets": [
            {
                "arch": "x86_64",
                "count": 1,
                "distro": "RHEL-7.5",
                "name": "rhel75",
                "variant": "Server"
            }
        ],
        "role": "bkr_server",
        "whiteboard": "Provisioned with linchpin"
    }
}
```

**Comment by Dannyb48** [comment]
@samvarankashyap @14rcole Yes, this is the problem. The hardcoded data I mentioned above is the new mock data. The linchpin.conf tied to this workspace has the following option set
```
[evars]
linchpin_mock = True
```
As soon as I set it to `False`, this workspace worked as normal. https://beaker.engineering.redhat.com/jobs/4028500

**Comment by samvarankashyap** [comment]
@14rcole Is this still an issue to be opened. 
looks like the beaker provider is working as expected it to be.

**Comment by 14rcole** [comment]
@samvarankashyap Nope, it seems fine to me
