### ISSUE TITLE
LinchpinAPI do_validation is always returning rc 0 even though validation fails on layout

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1578]
**Describe the bug**
When calling the LinchpinAPI `do_validation` function, it returns a tuple containing the return code, and the results of the validation. The` do_validation` always returns 'successful' because the rc is 0 but it's not until you run `do_action`, where it does another validation and throws a ValidationException error on the layout fields.

Looks like `do_validation` calls validator function `validate_pretty`, where as `do_action` is calling `validate`. In `validate_pretty` the only time the return code is changed to non-zero is if topology validation fails but not if `layout` or `cfgs` validation fails. `validate_pretty` should be returning non-zero for all schema key failures.

**To Reproduce**
Unfortunately this won't be reproduceable through the CLI because the shell `__ini__.py` doesn't even use the return code to detect failure, it uses the actual results data, and does a string check for certain key indicators.

1. Create a pinfile with improper layout schema
2. Open python console
3. Import `json`, `LinchpinAPI`, `LinchpinContext` modules
4. Use json module to load the pinfile data
5. Intialize a `LinchpinAPI` with a `LinchpinContext`
6. Provide the pinfile dict to the `LinchpinAPI.do_validation()`
7. Inspect that rc is 0 but results shows error in layout 

**Expected behavior**
If layout is specified in the pinfile and `do_validation` fails due to improper layout schema it should return a non-zero rc code.

**Comment by samvarankashyap** [comment]
@Dannyb48 Any update on this? 
We will be moving it to the next sprint until it is fixed.

**Comment by Dannyb48** [comment]
I will be working on it this current sprint.
