### ISSUE TITLE
Add support for CentOS 8

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1596]
LinchPin currently runs tests on CentOS 7.  Now that CentOS 8 is released, we should expand our test converage.  This will involve adding a Dockerfile and BuildConfig for CentOS 8 and adding CentOS 8 tags to relevant tests.  It will also require an update to our documentation

**Comment by maneeshmehra** [comment]
@14rcole: Do you feel we should describe what it means to enable support for CentOS8 within LinchPin ? Also, describing what are the steps towards adopting a new Operating System within LinchPin, what new tests must be added, what changes to our CI will be required, where would our documentation reflect support for a new OS as well as any gotchas/limitations we currently have etc.

**Comment by 14rcole** [comment]
Yeah, I can do that

**Comment by samvarankashyap** [comment]
centos8 is available as a target for testing on GitHub actions. 
This ticket can be invalidated
