### ISSUE TITLE
Test `01_azure_vm` is failing

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1600]
Azure VM test fails at the book log postup hook.  Output from the hook is below.

**Comment by samvarankashyap** [comment]
@14rcole Looks like syntax problem which also occurs when the parameters are incorrect.

**Comment by samvarankashyap** [comment]
@abraverm Any clue?

**Comment by abraverm** [comment]
1. delete\edit the log it contains  credentials
2. that's the issue I mentioned in google chat - there is some problem with cfgs, it tries to render __LOG__  but it just ends up '__log__' string.
