### ISSUE TITLE
Custom roles do not add info to topology_outputs

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1606]
The aggregation of the `topology_outputs_<whatever>` variables that store the data from provisioning each resource definition is hard-coded in the `gather_resources` role.  Any outputs that are not aggregated here will not have their inventories generated properly, which means that no custom ansible roles will be able to generate inventories.  This will need to be fixed

**Comment by samvarankashyap** [comment]
fixed by #1607
