### ISSUE TITLE
1.10.0 cloud-config doesn't work on libvirt host

### ISSUE THREAD

**Issue by johnbieren** [CentOS-PaaS-SIG/linchpin#1630]
**Describe the bug**
When provisioning VMs with linchpin 1.10.0, execution completes but ssh'ing to the nodes does not work if you are using a cloud-config setup

**To Reproduce**
1. Provision VM on rhel8.1 with libvirt provider that uses cloud-config
2. Try to ssh to provisioned VMs
3. Get connection refused

**Expected behavior**
ssh works

**Desktop (please complete the following information):**
 - linchpin 1.10.0
- RHEL 8.1

**Additional context**
Works on linchpin 1.9.2

**Comment by samvarankashyap** [comment]
@johnbieren Could you share the Pinfile too ? 
Thanks

**Comment by samvarankashyap** [comment]
fixed by #1636
