### ISSUE TITLE
linchpin init doesn't work

### ISSUE THREAD

**Issue by JunqiZhang0** [CentOS-PaaS-SIG/linchpin#1642]
**Describe the bug**
When run 'linchpin init', it shows below
Unable to clone git://github.com/CentOS-PaaS-SIG/linchpin@master
**To Reproduce**
Simply run linchpin init
**Expected behavior**
Create a folder including all the examples under workplaces folder

**Screenshots**

**Desktop (please complete the following information):**
 - Fedora 30
 - linchpin 1.10.0

**Comment by samvarankashyap** [comment]
@JunqiZhang0 I am unable to reproduce the error ! on my machine. 
fedora 30 
linchpin 1.10.0

**Comment by samvarankashyap** [comment]
@JunqiZhang0 There was an outage in GitHub it might be the cause of the error. 
could you re-confirm the bug with a fresh installation of linchpin?

**Comment by JunqiZhang0** [comment]
It's the local problem, just letted it go
