### ISSUE TITLE
Malformed inventory due to lowercase

### ISSUE THREAD

**Issue by yprokule** [CentOS-PaaS-SIG/linchpin#1690]
**Describe the bug**
When inventory is generated all the options are lowercased. 

That's break setting up ssh's `ProxyCommand`:

` -o ProxyCommand='ssh -W %h:%p {{ remote_user }}@{{ remote_host }}'` is rendered as

 `-o proxycommand='ssh -w %h:%p user@host.example.com'`

**To Reproduce**

1.  Add to inventory layout:
```
inventory_layout:
  vars:
    ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p 'user@host'"
```
2. Run `linchpin up` to generate inventory
3. Check generated inventory

**Expected behavior**
Options shouldn't be altered as lower and upper case keys might differe

(as in ssh example `-w` and `-W`)

**Version**
`linchpin version 1.9.2`

**Comment by Dannyb48** [comment]
@yprokule @samvarankashyap @14rcole 

I was able to reproduce in 1.9.2 but I also tested in 1.10.0 and latest develop branch and I do not see this issue anymore. So whatever was causing this looks to be fixed and will be available in the next release.

**Comment by 14rcole** [comment]
@yprokule Can you confirm that this bug still exists in 2.0?

**Comment by samvarankashyap** [comment]
@yprokule please re-open this issue if it is not fixed in latest release of linchpin
thanks
