### ISSUE TITLE
Packaging process disabled

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#1735]
Github package job was disabled due to unknown  AppImage job failure, the result is that new releases don't have neither AppImage or RPM packages

**Comment by probonopd** [comment]
If you like I can have a look, can you point me to a log file? Thanks.

**Comment by abraverm** [comment]
I don't know what exactly the error, but you can try build the image yourself (you will need docker):
```
cd appimage
docker build -t appimage-build appimage
./pkg2appimage-with-docker appimage.yml
```

**Comment by digitronik** [comment]
@probonopd its easy fix if you like work.

problem is with path... you need point `out/Linchpin*.AppImage` but make sure version should match :).
currently workflow taking version from `versions.py` which is not devel version.

Second thought better to fallow `rpm` job i.e. runtime parse with CLI.

**Comment by probonopd** [comment]
As our Docker expert, do you understand what the error is @TheAssassin?

**Comment by abraverm** [comment]
@probonopd, I fixed the job, you can download an AppImage from [my test release](https://github.com/abraverm/linchpin/releases/tag/test9) until the next official release of Linchpin

**Comment by Dannyb48** [comment]
@abraverm For some reason with this patch release of 2.0.2 an AppImage of Linchpin was not generated, or at least I can't find it. Any chance you can take a look?

**Comment by abraverm** [comment]
The package was not releases due to a bug with appimage job, it builds the [package from pip repository with older version](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/appimage/appimage.yml#L13) (2.0.1) and fails to find the artifact of the [current release version](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/.github/workflows/packaging.yml#L119) (2.0.2). The quick fix is using `sed` in the job or figure out how to expose the release source folder to appimage build script.
