### ISSUE TITLE
(2) Add check_ssh role from cinch to linchpin

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linchpin#174]
With the advent of post-provisioning actions, a problem presents itself, at least with OpenStack and cloud-init.  Here's a use case:

* provision an OpenStack instance with linchpin
* use linchpin to execute a post-provisioning Ansible playbook on the instance

The problem here is that when cloud-init is setting up SSH access on the newly provisioned host, any Ansible processes running during this time will fail to connect to the instance with an "SSH unreachable" error.  There is no retry logic built into Ansible itself to deal with this problem.  As such, in cinch we created a **check_ssh** [1] role which provides the necessary retry logic.

Since this scenario might be common to other scenarios cases beyond cinch, perhaps linchpin could implement this functionality directly and we could drop it from cinch.

[1] https://github.com/RedHatQE/cinch/tree/master/cinch/roles/check_ssh

**Comment by herlo** [comment]
This could be our first built-in hook. Then someone could just enable the post-provision hook. :) I like it!

**Comment by samvarankashyap** [comment]
@seandst As you might have already tested cinch playbooks for check_ssh . It would be great if you can post a github repository with linchpin workspace with example Pinfile, Hooks folder to make it work.

**Comment by herlo** [comment]
Putting it into LinchPin proper seems like a good choice as our first built-in hook. :)

**Comment by greg-hellings** [comment]
This issue should now be implemented using the `wait_for_connection` role since that was added to Ansible.
