### ISSUE TITLE
can't successfully buildh linchpin container followed by official documentation

### ISSUE THREAD

**Issue by chuanchang** [CentOS-PaaS-SIG/linchpin#1741]
**Describe the bug**
can't successfully buildh linchpin container followed by https://linchpin.readthedocs.io/en/latest/installation.html

**To Reproduce**
1. $ cd /root/Workspace/linchpin/config/Dockerfiles/fedora31
2. $ cp /root/Workspace/linchpin/config/Dockerfiles/init_libvirt.sh .
3. $ buildah bud -t linchpin .
4. $ buildah run linchpin -v /path/to/workspace:/workdir -- linchpin -w /wordir up

**Expected behavior**
can successfully run a linchpin container

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RHEL 8.2

**Smartphone (please complete the following information):**

**Additional context**
$ buildah run linchpin -v /path/to/workspace:/workdir -- linchpin -w /wordir up
error reading build container "linchpin": error reading build container: container not known

There are several questions for me: 1. buildah bud only generated a linchpin container image not a container,  and buildah run requires a <container_id/name> parameter, so it must be failed to follow cmdline in our documentation, I guess it may be podman not buildah command in here, or to use buildah from to generate a linchpin container before executing buildah run command 2. for '-v /path/to/workspace:/workdir', I want to know what is /path/to/workspace? is it linchpin work path or auth path? it has a little secret for users, although a Note is provided by documentation, could you give a available example? thanks!

**Comment by chuanchang** [comment]
```
# ls /root/workspace
PinFile

# buildah run -v /root/workspace:/workdir:rw linchpin-working-container -- linchpin -w /workdir up
Usage: linchpin [OPTIONS] COMMAND [ARGS]...
Try 'linchpin -h' for help.

Error: Invalid value for '-w' / '--workspace': Path '/workdir' is not readable.

# buildah run -v /root/workspace:/workdir:rw linchpin-working-container -- linchpin -w workdir up
/linchpin/workdir/PinFile not found. Please check that it exists and try again
```

**Comment by Dannyb48** [comment]
@abraverm can you help out here?

**Comment by abraverm** [comment]
> 1. buildah bud only generated a linchpin container image not a container, and buildah run requires a <container_id/name> parameter, so it must be failed to follow cmdline in our documentation, I guess it may be podman not buildah command in here, or to use buildah from to generate a linchpin container before executing buildah run command

Correct, podman\docker\... should be the right command for starting a container

2. for '-v /path/to/workspace:/workdir', I want to know what is /path/to/workspace? is it linchpin work path or auth path? it has a little secret for users, although a Note is provided by documentation, could you give a available example? thanks!

I think the auther meant [workspace](https://linchpin.readthedocs.io/en/latest/running_linchpin.html#workspaces). Regarding credentials, the [default path where Linchpin looks for credential files](https://linchpin.readthedocs.io/en/latest/running_linchpin.html#credentials-location) is at `~/.config/linchpin`, lets take the following topology as an example:
```
---
topology_name: ec2-new
resource_groups:
  - resource_group_name: "aws"
    resource_group_type: "aws"
    resource_definitions:
      - name: demo-day
        flavor: m1.small
        role: aws_ec2
        region: us-east-1
        image: ami-984189e2
        count: 1
    credentials:
      filename: aws.key
      profile: default
```
If your run `podman run linchpin -v /path/to/workspace:/workdir -- linchpin -w /wordir up` then by default it will look for credentials `aws.key` at `/root/.config/linchpin` inside the container. There are number of ways to handle this problem:
- mounting credentials file to `/root/.config/linchpin`, something like ` -v /path/to/aws/creds:/root/.config/linchpin` but when Linchpin executed it will generate number of files (logs, db, etc) and save it to the same folder.
- changing the credentials path by doing one of the following:
   * Environment variable `CREDS_PATH`, something like `podman run -e CREDS_PATH=/workdir`
   * [Linchpin config file](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/examples/workspace/linchpin.conf) that you can put in the workspace folder and change `default_config_path` or `default_credentials_path`
   * Command option `--creds-path`: `linchpin -w /workdir --creds-path /workdir up
`

**Comment by chuanchang** [comment]
@abraverm it's helpful for me, thanks! and please fix issue in documentation - https://linchpin.readthedocs.io/en/latest/installation.html

**Comment by chuanchang** [comment]
Please upgrade linchpin to 2.0.2 or other stable version in contrainfra/linchpin.

I rebuilt linchpin container image w/ linchpin 2.0.2, it works for me.

```
-------------8<----------------
PLAY RECAP *********************************************************************
localhost                  : ok=28   changed=4    unreachable=0    failed=0    skipped=27   rescued=0    ignored=0

Action 'up' on Target 'rhel-8.2' is complete

ID: 1
Action: up

Target                  Run ID  uHash   Exit Code
-------------------------------------------------
rhel-8.2                     1  5a542d          0
```

**Comment by abraverm** [comment]
@chuanchang , thank you for your feedback, I will fix the documentation and create a flow to update images.

**Comment by abraverm** [comment]
@chuanchang, ~~the images moved to [Quay.io|https://quay.io/repository/cpaas/linchpin?tab=tags], I will update the docs.~~
**Update**
The [Quay.io linchpin images|https://quay.io/repository/cpaas/linchpin?tab=tags] are not based on this repository Dockerfile. I've updated Docker Hub autobuild and the latest tag has 2.0.2. Future releases (tags) will also have their own image. If older version of Linchpin docker image is needed then I will build and publish it manually.
