### ISSUE TITLE
Failed to destroy beaker machine

### ISSUE THREAD

**Issue by lslebodn** [CentOS-PaaS-SIG/linchpin#1751]
**Describe the bug**
linchpin -v destroy failed with ansible error due to undefined variable

```
//snip
    TASK [beaker : convert set topo_output_resources from rundb] *******************************************
    skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
    
    TASK [beaker : Filter list for resources] **************************************************************
    fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'topo_output_json' is undefined\n\nThe error appears to have been in '/usr/lib/python2.7/site-packages/linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Filter list for resources\n  ^ here\n"}
     [WARNING]: Could not create retry file '/usr/lib/python2.7/site-
    packages/linchpin/provision/linchpin.retry'.         [Errno 13] Permission denied: '/usr/lib/python2.7
    /site-packages/linchpin/provision/linchpin.retry'
    
    PLAY RECAP *********************************************************************************************
    localhost                  : ok=5    changed=1    unreachable=0    failed=1
    
    ID: 3
    Action: destroy
    
    Target                  Run ID  uHash   Exit Code
    -------------------------------------------------
    machine-beaker               3  3da6a5          2
```

**To Reproduce**
1. Prepare beaker PinFile
2. linchpin up
3. linchpin -v down

**Expected behavior**
Machine returned without any problem

**Additional context**
 - OS: CentOS 7
```
bash-4.2# rpm -q python 
python-2.7.5-88.el7.x86_64
bash-4.2# pip freeze | grep linchpin
linchpin==1.9.2
```

**Comment by Dannyb48** [comment]
@lslebodn Looking at the code, I believe this is fixed in later versions. Can you try at least 2.0.2?

**Comment by lslebodn** [comment]
>  Looking at the code, I believe this is fixed in later versions. Can you try at least 2.0.2?

I can see jsut two commits which are not in 1.9.2 and they seems to be related to testing playbooks.

@Dannyb48 would you mind tell which commit fixed the bug?
Because IIUC linchpin 2.x does not support python2 anymore.

```
sh$ git log --stat -2 linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml
commit f82fbef8cd78edac5434b1416b464bf9b765f941
Author: Ryan Cole <rycole@redhat.com>
Date:   Mon Mar 23 12:02:16 2020 -0400

    Add support for molecule converge tests in beaker
    
    Add support for molecule converge tests in beaker and run the tests
    in github actions
    
    Signed-off-by: Ryan Cole <rycole@redhat.com>

 linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)

commit b82290016e56de4659839e37944e6eedda556e97
Author: Ryan Cole <rycole@redhat.com>
Date:   Thu Mar 5 11:25:00 2020 -0500

    Make beaker module pass molecule linting tests
    
    Signed-off-by: Ryan Cole <rycole@redhat.com>

 linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Comment by Dannyb48** [comment]
Hi @lslebodn the most recent commit on that list is where the changes to the teardown playbook were made.

f82fbef8cd78edac5434b1416b464bf9b765f941

Well, a workaround you could try is to explicitly set `generate_resources` to false in the linchpin.conf. 
```
[evars]
generate_resources = False
```
or pass that extra var on the command like 
```
linchpin up --env-vars generate_resources False
linchpin destroy --env-vars generate_resources False
```

Right now I'm basing it on the output you posted into the issue. This task that got skipped
```
TASK [beaker : convert set topo_output_resources from rundb] *******************************************
    skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
```
Is what sets the `topo_output_json` fact which is later used in the `Filter list for resources` task which is complaining that it is undefined. The reason that was skipped was because this evaluated false

```
 when: not generate_resources
```

**Comment by Dannyb48** [comment]
Hi @lslebodn did this help at all?

**Comment by Dannyb48** [comment]
@lslebodn any update on this?

**Comment by lslebodn** [comment]
Sorry for late reply.
I can confirm `generate_resources = False` helped even with `linchpin==1.9.2`
Is there some documentation(comemnts in the code)  for the `generate_resources` feature ?

Would like to know what is side-effect of such change.

**Comment by Dannyb48** [comment]
no worries, sorry for my late reply. 

Yeah you can look at this https://linchpin.readthedocs.io/en/latest/config_detail.html?highlight=generate_resources#generate-resources

It's a hold over from older versions of linchpin. They used to right their data out to file but now they store in a a nosql db called TinyDB. It shouldn't have any side effects, to be honest I'm surprised the original developers never deprecated this feature and removed it.

**Comment by Dannyb48** [comment]
@lslebodn any chance we can close this issue out?

**Comment by lslebodn** [comment]
> @lslebodn any chance we can close this issue out?

Yes; thank you for your comment
https://github.com/CentOS-PaaS-SIG/linchpin/issues/1751#issuecomment-693462998
