### ISSUE TITLE
Rewrite os_heat to remove python-openstackclient as dependency

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#216]
Python-openstack client  is responsible for frequent contextual version conflict in linchpin . 
python-openstack client is necessary for provisioning openstack heat templates.
In order to remove it, os_heat resource needs to rewritten in linchpin using ansible heat module.
Further, due to python openstack client, many unnecessary packages are installed , like
```
pbr!=2.1.0,>=2.0.0 # Apache-2.0
six>=1.9.0 # MIT
Babel!=2.4.0,>=2.3.4 # BSD
cliff>=2.3.0 # Apache-2.0
keystoneauth1>=2.18.0 # Apache-2.0
openstacksdk>=0.9.14 # Apache-2.0
osc-lib>=1.2.0 # Apache-2.0
oslo.i18n>=2.1.0 # Apache-2.0
oslo.utils>=3.20.0 # Apache-2.0
python-glanceclient>=2.5.0 # Apache-2.0
python-keystoneclient>=3.8.0 # Apache-2.0
python-novaclient>=7.1.0 # Apache-2.0
python-cinderclient>=2.0.1 # Apache-2.0
```
Resolving this issue would definitely reduce the disk footprint and version conflicts of linchpin .

**Comment by herlo** [comment]
@samvarankashyap You previously mentioned the ansible heat module was not sufficient for our needs. I assume this has now changed?

**Comment by samvarankashyap** [comment]
@herlo I believe now we can rewrite linchpin heat resource with ansible module without effecting the existing topology schema.

**Comment by herlo** [comment]
Ansible is moving the os_server module toward python-openstackclient. In further discussions, we've decided to start separating out each of the providers into their own packages. This will help alleviate dependencies, and allow users freedom of choice on which providers to use. Closing this ticket.
