### ISSUE TITLE
Create and Distribute LinchPin RPM

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#240]

**Comment by herlo** [comment]
Dependency hell has made this a challenge. We'll revisit when we have a better dependency structure. Thanks @greg-hellings for the work done so far.

**Comment by greg-hellings** [comment]
I'm literally only waiting for the final release of linchpin that can handle ansible >= 2.3.2.0, which is already implemented in the develop branch.

The moment that's done, I can resubmit my review request for RPMs to Fedora.

**Comment by herlo** [comment]
Oh, I thought there was more to this. I'll see about getting that done this week.

**Comment by herlo** [comment]
@greg-hellings, we targeted >= 2.3.1, I assume that would work?

**Comment by greg-hellings** [comment]
Yes, it's the >= that is the important part for packaging, not specifically the version.

**Comment by herlo** [comment]
@greg-hellings I think we updated the ansible >= 2.3.1 setting. Is there anything else waiting on this? Please note, there is one new dep, tinydb, but it's already packaged and shouldn't be any additional work for you.

Thanks!

**Comment by greg-hellings** [comment]
@herlo The following dependency is currently waiting on review before I can get back to linchpin packaging. https://bugzilla.redhat.com/show_bug.cgi?id=1495293

**Comment by greg-hellings** [comment]
Here's the current package request: https://bugzilla.redhat.com/show_bug.cgi?id=1441843

If someone wants to take it over, feel free.

**Comment by herlo** [comment]
@greg-hellings Thanks for the work on getting it reviewed. I'm sure it'll eventually get picked up if you don't have time now.
