### ISSUE TITLE
Drop support for schema_v3

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#243]
From recent discussions PR #236 . Its agreed upon to drop the support for schema_v3 from 1.1.0 release. 
Note:
However, schema_v3 continuous to work with the resource_group_types except openstack, aws, gcloud due to recent changes in authentication mechanism using auth_driver PR #236 .
Further , all the other playbooks for provisioning are to be updated in accordance with how authdriver parses files from --creds-path ref #76 
Moreover, It's also to be noted that eventually the way linchpin handles schema will be subjected to change w.r.to PR #235 in near future releases removing all the references to schemas.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reworking Schema](https://trello.com/c/pBfMFeHx/20-reworking-schema)

**Comment by herlo** [comment]
release of linchpin v1.5.0rc1 no longer uses schema_v3
