### ISSUE TITLE
(8) Create unique identifier for provisioned resources

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#284]
See #150 
See #144 

The concept here is that based upon the target data, topology and optional layout, we create a unique value that can be tracked for a specific provisioning action. This can be looked up properly and consistently.

**Comment by mrniranjan** [comment]
I would also like to have this feature

**Comment by arilivigni** [comment]
This feature IMHO already needs to be in linchpin to be useful.  If I am running this on multiple systems against one tenant or set of tenants this very easily could have collisions.  This is where some command line or other running execution option is essential.

**Comment by herlo** [comment]
@arilivigni at this point, we do have a feature that should land in 1.1 which allows us to track the individual provisioning components. However, this doesn't yet provide management of the unique identifiers on a job by job basis. It just puts the identifiers in place. 

While I don't disagree that this would be an awesome feature, I don't think LinchPin was originally designed to do things this way. My understanding was that it was intended to be idempotent, meaning that provisioning with one topology can be consistent. Obviously, with different credentials, or different topologies, the provisioning would produce different results. But all things being equal would not create new resources, but rather ensure that the topology looked as described.

The challenge is more complex than it appears on the surface. In some cases, people would actually want to have the same run do the same thing. This means that a provisioning is repeatable.

Another consideration is to determine how to differentiate. We could use a run_id (which is what we've implemented) to track individual jobs, but that then indicates there needs to be a way to store data on each action. It also means that each run is unique, and that to ensure a previous action can be repeatable, there must be a way to know how to re-run that specific action again.

The teardown action is another thing altogether. If you have performed 3 different provisioning actions, which one gets destroyed? Without some sort of tracking, this goes awry as well. We've made some decisions recently around this concept, but are still in the process of designing how the interaction will work. 

There's also the consideration of sharing topologies. If one person is provisioning on machine A, what's to say that when they go to provision on machine B that they don't want the same items provisioned again (or ensured that they are provisioned)? To that end, a unique identifier per machine likely needs to be in place. However, if they are unique, then the provision action would create two unique sets of systems. To allow for two different machines to provision (or ensure) only one set of systems, a flag will need to be set, or the unique identifier would need to be made the same.

It's clearly more challenging to enable both options, which it seems needs to happen. The structure has been planned, but the work has only started to accomplish this task. It's a definite priority, but with our limited resources, it may take some time to complete. Currently, the full feature is planned to land in version 1.5, but may happen sooner or later depending on demand and availability.

**Comment by herlo** [comment]
This is what we've come up with for addressing this issue.

Idempotency is on a provider-by-provider basis:
* aws doesn't support idempotent provisioning
* openstack, gce, and libvirt support idempotent provisioning

Unique transactions will be the default, with specific providers offering `--idempotent` flag.

Uses runDB to track by runID with combination of macid, pinfile, topology, optional layout, and then tagged with a unique date. This is then turned into a sha256 sum (or can use a user provided value) to track each transaction.

**Comment by herlo** [comment]
Currently, the dummy and os_server modules are working (no async support yet). I need to take the time to make gcloud, aws_ec2, and libvirt work. I expect to have something working by Friday and can demonstrate it early next week.

**Comment by herlo** [comment]
This has been resolved by #382, closing issue.
