### ISSUE TITLE
Allow locally-modified linchpin.conf to override only the values defined in that file.

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linchpin#286]
If a user would like to modify a setting in the default linchpin.conf, rather than making a copy of the entire file and modifying a single setting, a more ideal scenario would be to just define the single setting you want to change in your local linchpin.conf, and then have the rest of the settings fall back to the default linchpin.conf provided by the package.  As it stands right now I seem to need to copy the entire file to change one setting.  Having this sort of "override/fallback" behavior would make upgrades easier for users when the package-provided linchpin.conf changes as part of new releases of the software.

**Comment by herlo** [comment]
I thought this was the way it worked. I'll doublecheck this and if not, we can add this to the 1.1 spec.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LinchPin fetch 'workspace' data from remote](https://trello.com/c/MVhzX69m/27-linchpin-fetch-workspace-data-from-remote)

**Comment by herlo** [comment]
See #295 as the spec for this. Closing and moving discussion there. Thanks
