### ISSUE TITLE
Support variable expansion in layout files

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linchpin#287]
I've got a var in my layout file that I would like for linchpin to expand *before* it creates the output topology:

`ansible_private_key_file: "{{ workspace }}/keystore/mykey"`

In my case I'm keeping my SSH key in the linchpin workspace, and for my follow-up Ansible playbooks I would like to have this var expanded to the correct path so that those playbooks can find the correct SSH key.

**Comment by herlo** [comment]
If something is set as an extra var in linchpin.conf, it should be expanded. The only value that is built-in is lp_path, which evaluates to the linchpin library path. If you set that value in the [evars] section, it should be interpolated properly.

**Comment by greg-hellings** [comment]
Per my advice, David is going to skip putting variables into the layouts
file and use proper Ansible methodology of including a group_vars folder
alongside his inventory files. This will get picked up by subsequent
Ansible runs against the generated inventory and can directly leverage
values like {{ inventory_dir }} to give the relative path to the file.

**Comment by herlo** [comment]
Does that mean that this issue can be closed?

**Comment by robled** [comment]
I'm fine with closing this since @greg-hellings found a solution that removes my need for this.
