### ISSUE TITLE
Extension of linchpin.conf, support for named workspaces, and linchpin fetch

### ISSUE THREAD

**Issue by agharibi** [CentOS-PaaS-SIG/linchpin#292]
**Tasks to accomplish**
1. Override/Extend `linchpin.conf` from existing paths
2. Add support for named workspaces
3. Create `linchpin fetch` command
# Override/Extend linchpin.conf from existing paths
---

Currently, LinchpinCliContext search four paths in order (`$PWD/`,` ~/.config/linchpin/`, `/etc/`,  `/linchpin/library/path/`) to find a `linchpin.conf`. While this is sufficient for a first-found configuration, only one configuration file is loaded. It would be better if the order were reversed, and each additional configuration file would be extend and/or override the existing configurations. This is similar to the behavior already in place when using the get/set methods (`get_cfg()`,`set_cfg()`,`get_evar()`,`set_evar()`) in the `LinchpinContext` class.

Currently, most of this functionality resides in the cli version of this class, but it's the inherited class. Moving the lookup into the api class would benefit new classes (possibly a `linchpin/rest/context.py` in the future) which inherit from it. To accomplish this, two files would need to be modified: `linchpin/api/context.py` and `linchpin/cli/context.py`. 

**Modification of the `linchpin/cli/context.py` would consist of the following**
Remove the load_config as it stands, and copy it into `linchpin/api/context.py`, which will then be modified as below. Call the parent method, then possibly do additional work to handle any command-line specific adjustments

**Modification of `linchpin/api/context.py` would consist of the following**
Update the `load_config()` method to include lookups of the above four paths as stated, but instead of first-found, load each in reverse. Allow overriding and extending of any additional data from each of the remaining three files. The order cannot be controlled by the configuration file, as that would cause a rift in the space-time continuum.

# Named Workspaces

---
### Modify the configuration file
The current configuration file only supports a single workspace. To fix this, a new configuration section needs to be created that can support the function of multiple workspaces. Here's what a sample section would look like:

        [workspaces]
        <name_of_workspace1> = <file://path/to/workspace>
        <name_of_workspace2> = <git://path_to_workspace.git>

This configuration file would override/add to the current configuration file that is generated when linchpin init is executed. This structure would support the use of multiple workspaces along and would be easy to modify/access. The cli would refer to this file to find the path to the workspace whether it be local or remote.

### `Linchpin init`
Currently linchpin init, initializes a workspace in the environment variable WORKSPACE. However, with the newly proposed multiple workspaces support, if someone executes linchpin init and does not specify a name, the workspace will not be named. However, if a name is set, the workspace will be referred to as the set name with the path in the config file. For example: `linchpin init -n myWorkspace` or `linchpin init --name myWorkspace`
This command will initialize a new workspace and name it myWorkspace with the filepath specified in `$WORKSPACE` or if a `-w` is added, then at the path specified.
It it should like this in the config file:

    [workspaces]
    myWorkspace = /path/to/workspace

The `-n` flag can be used to name any workspace that has not been named at any time as well.
### `Linchpin up/destroy`
This command will change much like linchpin init. Once implemented, the user can specify which workspace to provision. If not specified, `$WORKSPACE` is used. Here is an example: `linchpin up -n myWorkspace` or  `linchpin down --name myWorkspace` This could mean that a user can provision a workspace that is not stored locally. The workspace would then be fetched using the remote protocol and stored in `/tmp` and provisioned that way.

 *An important thing to note is that these methods must be able to write back to the configuration file from `context.py`. Therefore, either the `set_cfg()` method needs to be modified or a new method needs to be written.*

# New command: `linchpin fetch`
---
### `linchpin fetch <type> <name_of_remote_workspace_src> <name_of_local_workspace_dest>`
*Types include: workspace, layout, topology, hooks, credentials, PinFile, etc*
This command will be able to retrieve any workspace, topology, layout, etc from a remote workspace. This would mean that the path to the workspaces specified as the arguments would be looked up in the configuration file under the `[workspaces]` header. If a name is given that does not have a specified path for it, an error would be thrown.

### `linchpin fetch <type> git://<url> file://<path>`
The user will also be able to specify the path to the root workspace with the cli as well. However, the root workspace must be specified as the directory that will be searched is going to be, for example, `root/layouts`. 

    linchpin fetch topology <name_of_remote_workspace> <name_of_local_workspace> 
    #copies from remote_workspace/topologies to local_workspace/topologies

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LinchPin fetch 'workspace' data from remote](https://trello.com/c/MVhzX69m/27-linchpin-fetch-workspace-data-from-remote)

**Comment by herlo** [comment]
@robled @greg-hellings @samvarankashyap @arilivigni Do you have any opinions, thoughts, or otherwise on these new features. @agharibi is going to be working these into v1.1 over the next few weeks.

**Comment by herlo** [comment]
This could potentially resolve #286, which I think would be pretty helpful.

**Comment by herlo** [comment]
With `linchpin init`, I'm trying to simplify concept of naming a workspace. 

If a user were to type `linchpin -w /path/to/workspace init -n bob`, would that imply that the user is wanting the namespace 'bob=/path/to/workspace'? 

Or would it be better to do something like `linchpin -w bob=/path/to/workspace init` and then if an `=` exists in the -w/--workspace option, linchpin would simply name the workspace.

**Comment by herlo** [comment]
Additionally, what about an already existing named workspace. For instance, if workspace `bob` already pointed to `/path/to/workspace` and the following happened:

`linchpin --workspace bob=/this/new/workspace init`

What would be the result? I'm guessing a prompt stating that the namespace `bob` already exists, querying whether to replace the value? Just some food for thought here.

**Comment by agharibi** [comment]
@herlo With ```linchpin init```, I don't think the way I have it set up in the documentation would be that confusing. Right now, it seems pretty straight forward and it makes the arguments easier to arrange. But I do see your point and I like having the '=' sign there too, so I am willing to do either one. Is there one format you prefer over the other?
Also, if a workspace already exists, an error should be printed to the console along with an option to replace the path to the named workspace.

**Comment by herlo** [comment]
@agharibi when you say documentation, do you mean this issue?

First off, the way Click works (you should check it out), the `-w/--workspace` option would always come after the `linchpin` bit, but before the `init`. To have an additional `-n/--name` option might be valuable here. My concern is that if a workspace isn't explicitly placed on the command line (or in the environment), and verified, it might do something unexpected. And if the value comes from the environment, maybe the user didn't mean to name it that way. Not sure if click can tell you whether the flag came from the command line or the env, but I am certain we can figure that out.

Anyway, if naming a workspace happens on the command line, it feels like the workspace and name options should be **explicitly** specified on the command line. Thoughts?

JUST FYI here. Keep in mind that technically, we'll be putting this in the linchpin.api part first, and then using it with the command line. Mainly because we want to expand that out to other possible user interfaces.

**Comment by seandst** [comment]
In order to make it easier to discuss the individual tasks, could this be split up into three distinct tickets?

**Comment by herlo** [comment]
@seandst the features are actually all related each other. The expansion of the config file, the workspace naming and fetching all relate to how the data will be landing into workspaces and managed. I think once we have some input, we might split it out, but the concepts are all related and difficult to split up without at least a description of the 'why' here.

**Comment by robled** [comment]
I would like to see **linchpin.conf** found automatically in the root of the linchpin workspace via the **-w** option and have the options stored there take precedence over other options defined in other linchpin.conf files.

**Comment by greg-hellings** [comment]
I would really like to see a PinFile option to name the inventory output file. That's the most pressing new feature (besides the user data option I already PR'd) to make my work behave well.

**Comment by herlo** [comment]
@greg-hellings that is a separate feature and not relevant to this discussion

**Comment by herlo** [comment]
@robled, I think this is a fair point to consider. I have $PWD, but that night not be the same as the workspace. What you are saying, is if `-w` is specified use that instead as if it were the working directory? I think this is doable.

**Comment by robled** [comment]
Indeed, **$PWD** could be different from the linchpin workspace.  In Jenkins, you typically run things from root of the Jenkins workspace, but specify some configuration data down the tree.  Consider this:

```
# pwd
/var/lib/jenkins/jobs/jslave-cinch-example-1-provision/workspace
# linchpin -w ./cinch-example
```

In this case I would want **linchpin.conf** stored at **./cinch-example/linchpin.conf** to be found and prioritized automatically via the -w option.

**Comment by herlo** [comment]
So, I think we need to consider two items here. 

First, the concept of building the linchpin configs from multiple configuration files, in order, allowing for extending and overriding. If we were to do the order `linchpin/library/path/` ,` /etc`, `~/.config/linchpin`, then `$WORKSPACE`(because $PWD is the workspace if nothing is set), we could then allow for the global stuff to be set by the config at `linchpin/library/path/`, and a user (you) could add sections, or override sections of the config located at `$WORKSPACE`. In this way, I think we get the best of both worlds.

Secondly, if a user wants to override the ENTIRE config file, this can be done. Simply copy the config file from the `linchpin/library/path` and modify it as needed, but leave the sections intact, even if they are empty.

I think this is the way it would work instead of a single file overriding another file. 

Does this work for you, @robled?

**Comment by agharibi** [comment]
This issue is being split into three issues: #295, #296, #297.
