### ISSUE TITLE
(5) Linchpin.conf: Override and Extend

### ISSUE THREAD

**Issue by agharibi** [CentOS-PaaS-SIG/linchpin#295]
Currently, LinchpinCliContext search four paths in order (`$PWD/`,` ~/.config/linchpin/linchpin.conf`, `/etc/`,  `/linchpin/library/path/`) to find a `linchpin.conf`. While this is sufficient for a first-found configuration, only one configuration file is loaded. It would be better if the order were reversed, and each additional configuration file would be extend and/or override the existing configurations. This is similar to the behavior already in place when using the get/set methods (`get_cfg()`,`set_cfg()`,`get_evar()`,`set_evar()`) in the `LinchpinContext` class.

Currently, most of this functionality resides in the cli version of this class, but it's the inherited class. Moving the lookup into the api class would benefit new classes (possibly a `linchpin/rest/context.py` in the future) which inherit from it. To accomplish this, two files would need to be modified: `linchpin/api/context.py` and `linchpin/cli/context.py`. 

**Modification of the `linchpin/cli/context.py` would consist of the following**
Remove the load_config as it stands, and copy it into `linchpin/api/context.py`, which will then be modified as below. Call the parent method, then possibly do additional work to handle any command-line specific adjustments

**Modification of `linchpin/api/context.py` would consist of the following**
Update the `load_config()` method to include lookups of the above four paths as stated, but instead of first-found, load each in reverse. Allow overriding and extending of any additional data from each of the remaining three files. The order cannot be controlled by the configuration file, as that would cause a rift in the space-time continuum.

The goal here would be to allow users to modify their own configurations. Each user may have different needs for their linchpin session and therefore this makes linchpin more flexible. All the user will have to do is edit their configuration file and linchpin will handle the parsing and implementation.

**Comment by herlo** [comment]
One note here on this specification, $PWD and $WORKSPACE only differ by whether the -w argument is passed. If it is passed, linchpin.conf can be found in the $WORKSPACE, and $PWD will be ignored.

**Comment by herlo** [comment]
Fixed by #301
