### ISSUE TITLE
(3) [SPIKE] Linchpin fetch

### ISSUE THREAD

**Issue by agharibi** [CentOS-PaaS-SIG/linchpin#296]
### `linchpin fetch <type> git://<url> file://<path>`
*Types include: workspace, layout, topology, hooks, credentials, PinFile, etc*
Linchpin fetch will be able to pull a workspace, layout, topology, etc from a remote repository and will put it in a locally specified location. When using this command, both a remote protocol and local path must be specified for it to work. For example:

    #Copies the topology files in the remote repository to the 
    #specified local workspace's topology directory
    linchpin fetch topology git://github.com/my/git/repo.git /path/to/workspace
   
One thing to note is that both paths must be pointing to the root workspace directory for it to work.

**The following is not going to be implemented for version 1.1:**
 `linchpin fetch <type> <name_of_remote_workspace_src> <name_of_local_workspace_dest>` 
Later, linchpin fetch will be able to be compatible with multiple workpaces. This means that the path to the workspaces specified as the arguments would be looked up in the configuration file under the `[workspaces]` header. If a name is given that does not have a specified path for it, an error would be thrown.

    linchpin fetch topology <name_of_remote_workspace> <name_of_local_workspace> 
    #copies from remote_workspace/topologies to local_workspace/topologies

**Comment by herlo** [comment]
These have been broken into three separate issues. Closing ticket now.
