### ISSUE TITLE
Named Workspaces

### ISSUE THREAD

**Issue by agharibi** [CentOS-PaaS-SIG/linchpin#297]
### Modify the configuration file
The current configuration file only supports a single workspace. To fix this, a new configuration file needs to be created that can support the function of multiple workspaces. Here's what a sample section would look like:

        [workspaces]
        <name_of_workspace1> = <file://path/to/workspace>
        <name_of_workspace2> = <git://path_to_workspace.git>

This configuration file would be different than the configuration file that is generated when linchpin init is executed. This will be called `workspaces.conf`, which should not be modified by the user. This should exist in `~/.config/linchpin/` and will be referenced when specifying the name to a workspace. Again, the only linchpin should modify this file.

### `Linchpin init`
Currently linchpin init, initializes a workspace in the environment variable WORKSPACE. However, with the newly proposed multiple workspaces support, if someone executes linchpin init and does not specify a name, the workspace will not be named. However, if a name is set, the workspace will be referred to as the set name with the path in the config file. For example: `linchpin init -n myWorkspace` or `linchpin init --name myWorkspace`
This command will initialize a new workspace and name it myWorkspace with the filepath specified in `$WORKSPACE` or if a `-w` is added, then at the path specified.
It it should like this in the config file:

    [workspaces]
    myWorkspace = /path/to/workspace

The `-n` flag can be used to name any workspace that has not been named at any time as well.
### `Linchpin up/destroy`
This command will change much like linchpin init. Once implemented, the user can specify which workspace to provision. If not specified, `$WORKSPACE` is used. Here is an example: `linchpin up -n myWorkspace` or  `linchpin down --name myWorkspace` This could mean that a user can provision a workspace that is not stored locally. The workspace would then be fetched using the remote protocol and stored in `/tmp` and provisioned that way.

 *An important thing to note is that these methods must be able to write back to the configuration file from `context.py`. Therefore, either the `set_cfg()` method needs to be modified or a new method needs to be written.*

**Comment by samvarankashyap** [comment]
Discussed this on June 10th. 
We team believe that its no longer necessary since workspace path is in place work linchpin init and up functions.
