### ISSUE TITLE
Search workspace/credentials for creds, or allow workspace/credentials to be defined in workspace/linchpin.conf

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linchpin#299]
In CI, it's common to store the full stack of things needed to make provisioning happen in source control, including credentials (properly secured, of course).  As such, looking for credentials outside of the linchpin workspace is less than desirable for CI, as when starting a build you would commonly check out *everything* needed to provision for that build from source control, and paths like **$HOME/.config** are not useful for this case.   

This improvement would help to serve a higher-level purpose, where if you point linchpin at a workspace checked out from source control, then from there it can find *everything* it needs to make things go, including **linchpin.conf** (there's already another ticket for finding this file in the linchpin workspace), as well as credentials.

**Comment by herlo** [comment]
I had assumed we had fixed this with #236. Essentially, you can pass the --creds-path option (or optionally, $CREDS_PATH env var) and point it into the workspace if you desire. Please give me more evidence why this option doesn't work? Maybe this is just an old ticket and can be closed?
