### ISSUE TITLE
Decrease the size of linchpin image on docker hub

### ISSUE THREAD

**Issue by rywillia** [CentOS-PaaS-SIG/linchpin#305]
The available linchpin image on docker hub [1] is over 1 GB in size. It would be great if the size of this image could be reduced. Having a large image takes longer for docker to pull the image locally. It took me almost 25 minutes to pull the image.

Maybe you can use this dockerfile [2] as a base? The size of this image is less than 600 MB.

[1] https://hub.docker.com/r/samvaran/linchpin/
[2] https://github.com/rywillia/dockerfiles/blob/master/linchpin/Dockerfile

**Comment by rywillia** [comment]
Yesterday I built a new image based on my Dockerfile above and was successfully able to run linchpin for OpenStack and OpenShift. I just wanted to give this information since the size of the image decreased by almost 1 GB. Please feel free to test that file to ensure other providers work as usual.

**Comment by samvarankashyap** [comment]
@rywillia I have significantly reduced the image size by pinning down the dependencies for source installation. Feel free to check it out . Thanks .

**Comment by rywillia** [comment]
@samvarankashyap That is great! I will pull the image and test it out. Just was curious as to why you need to install from source rather than by pip (pypi server)?

**Comment by samvarankashyap** [comment]
@rywillia We wanted to test the build from the latest commit by triggering the automated builds. At some point of time it would be a jenkins job. However, If you would like to have a build from the pypi server feel free to create one.

**Comment by rywillia** [comment]
@samvarankashyap Thank you for the detailed explanation. I think this issue can be closed now that the size has decreased by quite a good amount.
