### ISSUE TITLE
OpenStack Provisioning Using Count of 2 Fails

### ISSUE THREAD

**Issue by vi-patel** [CentOS-PaaS-SIG/linchpin#314]
I have a topology file that works fine for a single machine, when modifying the count to 2, it fails.  
I get the following error:

Target 'target': TASK: openstack : provisioning os_server resources with provided auth failed with error '(400) Client Error for url: http://<ip_address:port>/v2/bf4de4c330ee47d6937af31fd5c71a18/servers Bad network format: missing 'uuid''

*Tested in linchpin 1.0.1 and 1.0.2 - same error in both

**Comment by herlo** [comment]
Can you try this directly with the ansible module? I wonder if that's where the issue is happening. @samvarankashyap can look further as well, if needed.

**Comment by herlo** [comment]
Also, this seems similar to #335. I wonder what is going on here.

**Comment by samvarankashyap** [comment]
@vi-patel Please check #338 it resolves the above issue . 
Thanks
