### ISSUE TITLE
(5) Update documentation of topology examples

### ISSUE THREAD

**Issue by vi-patel** [CentOS-PaaS-SIG/linchpin#315]
The example topologies are out of date, can they be updated:

http://linchpin.readthedocs.io/en/latest/topologies.html
https://github.com/CentOS-PaaS-SIG/linchpin/tree/develop/linchpin/examples/topologies

**Comment by herlo** [comment]
I'm sure some of the topologies are out of date here. Can you specify which you have run into that are not accurate? We're working on better documentation for this, but could use some help in this area.

Thanks

@herlo

**Comment by vi-patel** [comment]
I was specifically working on OpenStack, and I don't think any of those were valid anymore.

**Comment by herlo** [comment]
I think between this issue and #317, it's clear these need to be updated. It's probably time to pare the examples down to a few that work and get updated each release.  @samvarankashyap what do you think?

**Comment by herlo** [comment]
@samvarankashyap and @herlo discussed this today. The plan is to put in a simple and complex example for each of the core (ec2, openstack, gcloud, libvirt) providers. Additionally, there will be some examples of combining these providers in a single topology. The rest of the examples will be moving to a contributor repository and noted that they may not be up-to-date.

**Comment by herlo** [comment]
Closed by #436
