### ISSUE TITLE
Can the  output in resources be simplified

### ISSUE THREAD

**Issue by vi-patel** [CentOS-PaaS-SIG/linchpin#316]
Can the output for the provisioners created in the resources directory be simplified, maybe only have one level and some consistent keys across different the different provisioners to simplify retrieving output from automation tools.  They seem to have complex output with multiple levels and specific output for each provisioner.  This makes it difficult for automation to switch between different provisioner options w/o having to write a specific parser for each provisioner.

**Comment by herlo** [comment]
@vi-patel I'm not exactly sure of your goal with the resources outputs. However, they are structured with the data returned from each provider. I do have a plan to simplify that data with a distiller class, it just hasn't yet been implemented. The idea was to take the resources outputs as they exist and pare them down to something that could be used to generate an inventory, or groupings in whatever way desired. I think this concept fits your request as well. 

What do you think? Would this serve you well? Would you be willing to contribute something here? 

Thanks

@herlo

**Comment by vi-patel** [comment]
We were planning to provision machines using linchpin, than we have objects for host machine in our framework.  So we were planning to use the data from the resources output, to create that object.

**Comment by herlo** [comment]
If you have a look at the output_writer playbook in 'linchpin/provision/roles', that is where the bulk of the work is done to gather the data and output the resources to the file. In the future, we're working on a mechanism to filter the data to the right places. We don't have a ton of manpower at the moment, however, so it may take a bit of time to complete. If you have resources to help with the work, it could go faster.

**Comment by herlo** [comment]
#284 is the ticket for the plan described above.

**Comment by herlo** [comment]
I think the work we've done around the runDB may address this issue. I've reached out to @tvieira to meet about it in the near future. Hopefully this will be resolved by that work.

**Comment by herlo** [comment]
I think this issue may be resolved by #382. The upcoming `linchpin journal` tooling should provide useful output functionality to gather data from a particular provisioning run. I'll update this ticket when it is completed.

**Comment by herlo** [comment]
Closed with completion of #418
