### ISSUE TITLE
Linchpin to handle provisioning if the resource already exists

### ISSUE THREAD

**Issue by rywillia** [CentOS-PaaS-SIG/linchpin#321]
I was asked to share my linchpin files (PinFile, credentials, layout, topology) with someone else to re-create the exact same environment of the resources that I have created. They go to run linchpin up with my same environment and the result is success (inventory file created). If you compare the files, the machine is the same (IP addresses match). This would be a problem if we are both modifying configuration settings on the exact same machine (when ideally thinking we got two different resources provisioned). I think this is a bug but not sure if this is the native functionality of linchpin.

It would be great if linchpin appended a random couple characters to the end of the resource name to make it unique. This would potentially resolve the problem of stepping on each other if we shared identical linchpin files. The other approach could be to just fail the provisioning right away if the resource was found. What do you think about this?

**Comment by herlo** [comment]
I think the concepts in #284 may address this request. Essentially, the unique identifier would be per user and thus check to see if the user had already provisioned the data.
