### ISSUE TITLE
Data Passthrough

### ISSUE THREAD

**Issue by vi-patel** [CentOS-PaaS-SIG/linchpin#322]
Can you add a key that can be used for data pass through.

For example, if I added a key called unique_key into the topology file of a machine, after the machine is provisioned, can this key be added to the output of that machine in the resources output?

**Comment by samvarankashyap** [comment]
@vi-patel Outputs are generated by the respective cloud provider , I am not sure there is a way to change this . However, incase of amazon instances if you user provides resource_group_vars they are automatically added as tags for aws ec2 instances
```
resource_group_vars:  
    - resource_group_name:"name of the grp"
       key1: val1 
```

**Comment by vi-patel** [comment]
I believe the only way the data passthrough would be useful is if it were available in a consistent way for every provider.

**Comment by greg-hellings** [comment]
What data are you interested in passing through?

**Comment by vi-patel** [comment]
I wanted to pass through a unique key id for each machine I provisioned. (Say I wanted to provision 5 machines w/ one linchpin call, i would have 5 host objects, each with a unique identifier, and I use linchpin to provision the 5 resources, but then my issue is trying to map the output of each machine from linchpin's output to the original 5 host objects, if I was able to pass a the unique key I could easily map linchpin's output to my host objects.)

**Comment by samvarankashyap** [comment]
@vi-patel : couldn't you map resource_name in linchpin topology with the cloud_provider name key value inside output ?

**Comment by vi-patel** [comment]
@samvarankashyap not all cases.  For example Beaker, the output really doesn't map to a resource name.  I was thinking about this for a while, and it seems the best available option to me is first match what provider I'm using, then if there are multiple resources try to map multiple keys based on that provider, but it gets complicated fast, and impossible checking for uniqueness if there were 2 machines w/same keys.

**Comment by tvieira** [comment]
The context for this request/issue is that we trace all machines life cycle. We save its metadata in a database when the request is made and we update the database as the provisioning process progress. In this case, @vi-patel is trying to gather the information from each host after it has been provisioned and set the status of each instance in the database - the unique reference would help us match each node. For instance, if we request 5 machines, when the machines are provisioned we want to update, for example, the IP address for each machine. We also can fail a job if one of these machines fail (or retry provisioning it) and update the database so the client that requests the job knows which machine failed and what are the IP for each machine that was successfully provisioned.

**Comment by rywillia** [comment]
@samvarankashyap Could you please explain how **resource_group_vars** works? When you say tag, is this a tag associated with the instance created like metadata for an OpenStack instance? I was searching through linchpin source code and this does not seem to apply to all providers. We are primarily focusing on OpenStack and Beaker. I just tried setting this resource_group_vars for an OpenStack resource and could not find this information I set within the resources output or the instance metadata.

Would it be hard to add a new feature as @vi-patel suggested? If the user defines a key within a resource definition such as **unique_key** or even a generic key that is a dictionary allowing the user to define as many key:values as they wish. Then this data could be wrote out within the **output_writer task** to the resource output. This would allow the ability to parse the output to match on a unique key ID to map the resource provisioned IP address within a database.

**Comment by samvarankashyap** [comment]
@rywillia 
Amazon provides feature support for users to set key value pairs to the resources provisioned. 
For openstack its not implemented yet in linchpin though meta is supported by ansible modules. 
Am not sure whether output returned by os_server module has the instance meta_data set . 
Please feel free to raise a issue to support meta data for os_server .

**Comment by herlo** [comment]
We are tracking the unique id issue in #284. Please comment there for further discussion.
