### ISSUE TITLE
RFE: Break out bkr_info/bkr_server into proper ansible module

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#327]
It seems we bundle some libraries in linchpin that should really be bundled in another package. In this case, Ansible modules, should go into Ansible. This issue is to track getting bkr_info and bkr_server moved over.

**Comment by seandst** [comment]
I'm not likely to work on this, and I don't think any of the other assignees will be working on it either. I recommend unassigning this issue, if not just closing it.

**Comment by samvarankashyap** [comment]
Moving the ticket to backlog will be revisited again
