### ISSUE TITLE
Break out gce2 into proper ansible module

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#328]
It seems we bundle some libraries in linchpin that should really be bundled in another package. In this case, Ansible modules, should go into Ansible. This issue is to track getting gce2 moved over.

**Comment by samvarankashyap** [comment]
@herlo gce2 is module is copied down from ansible 2.3
If ansible 2.3 is installed we can change the playbooks to use gce module to run instead of gce2

**Comment by herlo** [comment]
@samvarankashyap and @herlo discussed this and agreed 2.3.1+ is a better direction. Core providers should in all cases support ansible 2.3.1+. Tests need to be written to accommodate each provider.
