### ISSUE TITLE
Break out openshift into proper ansible module

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#330]
It seems we bundle some libraries in linchpin that should really be bundled in another package. In this case, Ansible modules, should go into Ansible. This issue is to track getting openshift moved over.

**Comment by samvarankashyap** [comment]
@herlo : from ansible 2.5 we have openshift raw module 
[https://docs.ansible.com/ansible/2.5/modules/openshift_raw_module.html](https://docs.ansible.com/ansible/2.5/modules/openshift_raw_module.html)
Should we be start supporting that instead ? 
@greg-hellings @robled

**Comment by greg-hellings** [comment]
Unbundling things is a great way to go. You have to make sure you either have your minimum Ansible version bumped up far enough, or you have to detect which version of Ansible is in use and make the appropriate play based on that, if you aren't ready to move up the minimum version, yet. But go for it!

**Comment by herlo** [comment]
@samvarankashyap I think for now, we shouldn't keep changing the module. But we can put that into the plan for the future when we decide to move the minimum version of ansible to 2.5+.

**Comment by herlo** [comment]
I think for now, this issue has been satisfied by #622. Closing issue.
