### ISSUE TITLE
Generate inventory names according to topology names, when possible

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linchpin#332]
Taking, as an example, OpenStack. When I spin up a host in my topology and name it "foo" and ask for two of them, my generated inventory looks something like this:
```
10.0.0.1
10.0.0.2

[group1]
10.0.0.1

[othergroup]
10.0.0.1
10.0.0.2
```

It would be much nicer if these were to be generated according to such a pattern:
```
foo1 ansible_host=10.0.0.1
foo2 ansible_host=10.0.0.2

[group1]
foo1

[othergroup]
foo1
foo2
```

This would allow referencing hostvars from a specific one of the hosts without jumping through some convoluted hoop of needing to grab the hostname based on its membership within a particular group, etc. Since those friendly identifiers are generated deterministically from the topology information, an inventory such as I proposed would be much easier to work with than one that simply refers to the ephemeral hostname/IP address that comes down from the provisioner's subsystem.

**Comment by herlo** [comment]
Greg, what I think you want already exists. Maybe I'm missing something though.

For instance, if I have the following layout for a single node topology:

```
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 1
      host_groups:
        - example
```
It produces the following from my libvirt topology:

```
[example]
192.168.71.165 hostname=192.168.71.165 

[all]
192.168.71.165 hostname=192.168.71.165 
```

The only thing that has to happen here is to have the vars section at the top of the layout explain what variables need to be interpolated. Currently, __IP__ is the only one available as there hasn't been any additional requests.

Does this address your issue?

**Comment by greg-hellings** [comment]
No, this isn't what I'm looking for. Notice that the host is still named "192.168.71.165" in the inventory. I want that name to be based on its topology (not layout) name. For instance, with the following topology for openstack:

```
resource_groups:
  - resource_group_name: foo
    res_group_type: openstack
    ...
    res_defs:
      - res_name: bar
        ...
```

This will generate a host in OpenStack named "foo_bar1". I want that same name to be in the topology instead of the IP address as the default name. That way the inventory name from your layout would look like:

```
[example]
foo_bar1 hostname=192.168.71.165

[all]
foo_bar1 hostname=192.168.71.165
```

**Comment by herlo** [comment]
That is not how it currently works. If you want it to do that, you'll have to write a postup hook to generate the hostname based upon the topology data. The context provided in the hooks section would provide this data so you could generate your own inventory. In that case, don't provide a layout, just write a hook that does what you want. 

One note on this is that we can likely add a new interpolation to allow the resource_group_name and res_name to be interpolated in some way, but that it's not currently a thing that's available.

**Comment by greg-hellings** [comment]
I get that it doesn't work that way. I'm asking that it work that way. As it currently works, there is no reasonable way to reference hostvars from one system to another. My current use case is:

* Allocate two hosts
* Assign one host to be the server system
* Assign one host to be the client system
* Configure the server (this requires no data about the client)
* Configure the client to connect to the server (this requires, at the minimum, the IP address of the server)

Currently, to obtain the server's address, the only reliable way to get this is through the Ansible variable ``{{ hostvars[groups['server'][0]]['ansible_default_ipv4'] }}`` because the inventory host name is not predictable. Therefore, it is useless noise. If the inventory host name was predictable, then I could address it directly as ``{{ hostvars['hosts_server1']['ansible_default_ipv4'] }}``

**Comment by herlo** [comment]
Ok. I think I get what you are saying. The predictability of which machine is which is actually deterministic. It might not have the names as you mentioned, but the way it works is that the first group specified in the `host_groups` section of the layout should always be the first host from the resources. The second would be the second host, and so on. 

What you are asking for means that if a user wanted to have a host name associated with it, this would be it. However, that's not resolvable in each case, since DNS records don't necessarily map to the names given in the topology. Maybe there's some middle ground to gain here, though. It's just that changing the entries in the inventory to hostnames isn't a guarantee of anything. I also don't want to promise something in the core functionality where it changes what is expected. 

It turns out, the generation of this data is completely controlled in the inventory_gen playbooks. Each provider has to have one, as I suspect you know. The duffy one, for instance, uses the hostnames, because they are predictable and they're in the DNS on the CentOS CI environment. If we were to model something in the inventory_gen playbooks that allowed for you to provide a hostname based upon the topology, I could see that as doable. However, it would also need to promise that the hostnames would be resolvable in some way. I'm not sure that part can be promised with the way it's working.

To modify inventory_gen to make it the way you want it seems a fair bit of work. I can't say when it would work that way, nor can I say that it is something that we really want to deliver. Hooks seems like a much simpler solution to workaround the limitation of the inventory generation process.

**Comment by greg-hellings** [comment]
You've pretty well hit on the crux of what I'm asking for in this RFE.

So Ansible's dirty little secret is that the name in the inventory does not
have to be resolvable as either an IP address or a hostname. When
attempting to contact a remote host, Ansible will first attempt to connect
to the machine defined by the "ansible_host" variable, which is required to
be a resolvable address or undefined. If that value is undefined, then
Ansible attempts to use the value of inventory_hostname. In all of the
generators that I've seen, the IP address (or hostname, in the case Beaker,
etc) is assigned to the inventory_hostname slot. Which works fine for
connection. But it doesn't *have* to be set in that slot, if the
ansible_host variable is defined.

Since the deterministic groups are a valid workaround, I've been leveraging
them in my playbooks. But I wanted to put out this request to see if the
rest of the team was willing to make this change. It's not necessary from a
technical standpoint, but it would make using linchpin generated
inventories much easier. I'd be happy to schedule in the work for the
future as a low-priority task myself.

**Comment by herlo** [comment]
Consider creating a custom hook for this work. We'd be happy to help you understand how hooks work to get this bit working.

**Comment by mrniranjan** [comment]
@herlo Could you have a small write up on using hooks using simple example (like setting hostnames post provisioning)?

**Comment by herlo** [comment]
### Pinfile
```
os-single-test:
  topology: openstack-single.yml
  layout: openstack-single.yml
  hooks:
    postup:
      - name: ping
        type: ansible
        context: True
        actions:
          - playbook: os_ping.yaml
            extra_vars: {"ansible_ssh_private_key_file": "/home/herlo/Projects/rh/git/atomic-ci-jobs/project/config/keys/ci-factory"}
```
### Topology
```
$ cat topologies/openstack-single.yml 
---
topology_name: os-single
resource_groups:
  - resource_group_name: openstack-single
    resource_group_type: openstack
    resource_definitions:
      - name: resource
        type: os_server
        flavor: m1.small
        image: rhel-7.2-server-x86_64-released
        count: 1
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
        fip_pool: 10.8.172.0/22
    credentials:
      filename: clouds2.yaml
      profile: ci-osp
```

### Layout
```
$ cat layouts/openstack-single.yml
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 1
      host_groups:
        - example
```

### Hook
```
$ tree hooks/ansible/
hooks/ansible/
└── ping
    └── os_ping.yaml

$ cat hooks/ansible/ping/os_ping.yaml 
---
- hosts: example
  tasks:
  - name: ping
    ping:
```

Some things to note. Hooks has a `context: True` flag. This takes the outputs from our system and uses the inventory which was generated as the component to use to determine the group or some such.

From that, you can see that the layout shows group `example`. A corresponding `hosts: example` lives in the `hooks/ansible/ping/os_ping.yaml` file. This is how things are mapped. To that end, the only real work needed here is to have a layout defining the groups of machines, then applying the hook to the group.

I could have easily taken this code and applied it to a much greater example, but I'll leave that for the reader. 

Cheers,

herlo
