### ISSUE TITLE
'linchpin up' fails when provisioning basic libvirt instance

### ISSUE THREAD

**Issue by robnester-rh** [CentOS-PaaS-SIG/linchpin#337]
Following the guide at http://linchpin.readthedocs.io/en/v1.0.2/getting_started.html (also with 'latest' and 'develop' tags), I receive the following error when performing `linchpin up`:

```
~: linchpin up
	to retry, use: --limit @/home/rnester/miniconda3/envs/linchpin/lib/python2.7/site-packages/linchpin/provision/site.retry
        Target 'example_target': TASK: libvirt : ensure local_image_path directory exists failed with error 'MODULE FAILURE'

```
I have confirmed that the default image storage location directory (/var/lib/libvirt/images) exists:
```
~: ll /var/lib/libvirt/images/
total 4
drwxr-xr-x. 2 root root 4096 Aug  4 12:21 linchpin

```
and that the CentOS image is being downloaded to the linchpin subdirectory there:
```
~: ll /var/lib/libvirt/images/linchpin/
total 1114952
-rw-r--r--. 1 root root 898236416 Aug  4 12:21 CentOS-7-x86_64-GenericCloud-1608.qcow2
-rw-r--r--. 1 root root 248569364 Aug  4 12:21 CentOS-7-x86_64-GenericCloud-1608.qcow2.xz

```

**Comment by herlo** [comment]
Running `linchpin -v up` will help as we discussed this morning on bjns. However, the conversation was clear that the getting started guide needs an update to use the dummy module. I'll put this into a ticket with an eventual goal of a choose your own adventure (Libvirt, AWS, GCE, openstack) option after running through the dummy provision.

**Comment by herlo** [comment]
I believe this was fixed with a conversation via IRC. Please reopen if this is not the case.
