### ISSUE TITLE
Feature request: linchpin hooks : failhooks , nohooks, runhooks  flags while linchpin up

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#339]
Currently linchpin runs hooks by default inside the Pinfile
For example if the user would like to do following things there isnt any option:

- Fail all hooks when one hook fails ( --failhooks)
- Donot run hooks over provisioned instances ( --nohooks)
- Runhooks over provisioned instances . Do not reprovision instances ( --runhooks)
- Run a specific hook by their names ( --runhooks name1, name2 )

The above can be achieved by passing flags to linchpin up and linchpin destroy commands 

@herlo Anythoughts /additions to features are appreciated

**Comment by herlo** [comment]
Reference #241 for another conversation around this...
