### ISSUE TITLE
Provide mechanism for greater verbosity

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linchpin#347]
Currently the "verbose" option is a flag. Ansible (following the lead of ssh) provides for a count of up to 4 levels of verbosity by increasing the number of times the flag is present (e.g. greater verbosity can be had by passing "-v", "-vv", "-vvv", and "-vvvv").

Improve linchpin to permit passing multiple -v options, which would be passed through to the underlying Ansible calls to increase its verbosity.

**Comment by herlo** [comment]
There is a grand problem with the API for this feature. I agree that we should have further verbosity. The challenge is that with the API, it's a bug we have yet to sort out. I think maybe that 2.3 has resolved this or something as the issues I had seen previously have disappeared from the ansible issues on Github. To that end, I've been working on a better bit of tooling for more verbosity in LinchPin overall, though it may take some time to get to with the resources we have at the moment.

**Comment by herlo** [comment]
Going to try to identify this and get it to work in 1.5.1 or 1.5.2.
