### ISSUE TITLE
Error fetching network list: __init__() got an unexpected keyword argument 'global_request_id

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#349]
When trying to provision on openstack, linchpin fails with error:

`
            "", 
            "TASK [openstack : provisioning os_server resources with provided auth] *********", 
            "fatal: [localhost]: FAILED! => {\"changed\": false, \"extra_data\": null, \"failed\": true, \"msg\": \"Error fetching network list: __init__() got an unexpected keyword argument 'global_request_id'\"}", 
            "\tto retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/site.retry", 
`

pip list:
linchpin (1.0.2)
openstacksdk (0.9.18)
python-openstackclient (3.12.0)

OS:
Fedora26

**Comment by mrniranjan** [comment]
This issue occurs because of keystoneauth1 (3.2.0), if i downgrade to keystoneauth1 (3.1.0), it works

**Comment by mrniranjan** [comment]
similarly on Fedora26, i had to degrade shade version to 1.19.0 , i think on the latest version of shade(1.23.0), it gives the below error:

AttributeError: 'ShadeAdapter' object has no attribute 'get_api_major_version'

**Comment by gsr-shanks** [comment]
+1

I am hitting similar issues. Provisioning works after downgrading the packages to the version mentioned above in this issue. Please have this resolved.

**Comment by herlo** [comment]
I believe this has been resolved by PR #351. Please reopen if this is not the case.
