### ISSUE TITLE
Set hostnames after provisioning 

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#350]
Currently in our internal openstack deployment or beaker, The ipaddress assigned to instances are added in DNS, So is there a way in post hookup , we could do a reverse lookup of the ip addresses and set the hostnames on the systems. 

Or if we want some custom hostnames to be set and update /etc/hosts too, is there a way to achieve this through hooks.

**Comment by herlo** [comment]
I suspect you could easily write a bit of code, then add it as a postup hook that would modify /etc/hosts or do reverse lookups for you.
