### ISSUE TITLE
Use single beaker job when defining multiple resource groups in single topology

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#357]
Currently when we provision multiple resources using resource group  Example:
`
topology_name: beaker_topo
resource_groups:
- resource_group_name: beaker_1
  res_group_type: beaker
  job_group: idm
  whiteboard: linchpin provisioning smartcard1 on ['x86_64']
  recipesets:
  - distro: RHEL-7.4
    arch: x86_64
    variant: server
    keyvalue:
    - MEMORY>1000
    - DISKSPACE>20000
    hostrequires:
    - tag: processors
      value: 1
      op: '>='
    - tag: device
      type: network
      op: '='
    count: 1
- resource_group_name: beaker_0
  res_group_type: beaker
  job_group: idm
  whiteboard: linchpin provisioning smartcard1 on ['x86_64']
  recipesets:
  - distro: RHEL-7.3
    arch: s390x
    variant: server
    keyvalue:
    - MEMORY>1000
    - DISKSPACE>20000
    hostrequires:
    - tag: processors
      value: 1
      op: '>='
    - tag: device
      type: network
      op: '='
    count: 1
`

The above creates 2 beaker jobs, Instead can it create a single beaker job with 2 installation tasks ?,

**Comment by greg-hellings** [comment]
By the construction of Linchpin, this will necessarily execute two calls to Beaker. Can you test putting both of those items into the same recipesets array and try it? That *should* give you one job. If it doesn't, I can look into modifying Linchpin to support that functionality. However, when you have two different resource groups defined in your topology that is going to require two different job invocations.

**Comment by mrniranjan** [comment]
Can you give an example or array here.

**Comment by greg-hellings** [comment]
Please delete the lines from `resource_group_name: beaker_0` through the second line that reads `recipesets:`. That should combine the two sets of recipes into a single job. At least, that's my understanding. Please let me know if that works for you or if that's not what you're looking for.
