### ISSUE TITLE
Docs: virtualenvwrapper orphan dependency

### ISSUE THREAD

**Issue by cevich** [CentOS-PaaS-SIG/linchpin#359]
It's listed as required for installation here http://linchpin.readthedocs.io/en/develop/installation.html#installing-linchpin but there's no other reference to it as a dependency.  Also, there's no mention w/n I can just use a regular ``virtualenv`` or not.  This is troubling since could block someone at the very first step!

**Comment by herlo** [comment]
Technically, virtualenvwrapper is not required to run linchpin. However, the docs should state that to make the installation work in the way they are described, that it should be installed. I'll mark this one to update that in the docs.

Thanks!
