### ISSUE TITLE
docs: Wheres the docs and tests?

### ISSUE THREAD

**Issue by cevich** [CentOS-PaaS-SIG/linchpin#360]
Installation mentions:

```
(linchpin) $ pip install linchpin[docs]
(linchpin) $ pip install linchpin[tests]
```

However there are no details on where the docs are located, nor how to run the tests.  There should be a 'hacking' section or at least include how to utilize virtualenv-installed ``linchpin[docs]``.  It'd be nice if the tests could be run from there as well, but at a minimum running them should be documented somewhere obvious.

**Comment by herlo** [comment]
As part of the setup.py, docs and tests sections exist.

```
# cat setup.py
... snip ...
    extras_require={
        'krbV': ["python-krbV"],
        'beaker': ['beaker-client>=23.3'],
        'docs': ["docutils", "sphinx", "sphinx_rtd_theme"],
        'tests': ["nose", "mock", "coverage", "flake8"],
        'libvirt': ["libvirt-python>=3.0.0", "lxml"],
... snip ...
```
And not that you'd know we're running travis-ci tests, but this gives the basics of what we do right now.

```
$ cat .travis.yml 
sudo: false

language: python

python:
  - "2.7"
#  - "3.6"

cache: pip

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install .
  - pip install .[tests]

script:
  - flake8 --exclude=\.eggs,tests,docs --ignore=E124,E303 --max-line-length 80 .
  - nosetests -s linchpin/tests/{cli,api}/*
```

We made an attempt at what you refer to as the 'hacking' section in @ https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/CONTRIBUTING.rst. It doesn't cover testing or generating docs, however. I'll leave this ticket open to address that specifically.

Thanks!

**Comment by cevich** [comment]
Ya, looked at ``.travis.yml`` but didn't consider looking at setup.  In ``CONTRIBUTING``, maybe after the 'making a change" section (or part of it) would be a good spot.  For example:

Testing:

If you'd like to test your commit before pushing:

1.  make sure you have all the ``extras_require`` packages installed, as listed in ``setup.py``.
2.  From the repository-root, follow the ``install`` and ``script`` sections of ``.travis.yaml``
3. You'll know the tests passed if all script commands exit 0
