### ISSUE TITLE
RFE: Extend linchpin to support digitalocean Api

### ISSUE THREAD

**Issue by cmoulliard** [CentOS-PaaS-SIG/linchpin#376]
Can linchpin be extended to support [digitalocean](https://developers.digitalocean.com/documentation/v2/#droplets) ?

From "srallaba"	
linchpin is highly dependent on ansible modules. Since the digital ocean ansible module is already posted on ansible2.4 its very easy to implement as a part of ansible

**Comment by samvarankashyap** [comment]
Moving feature to backlog shall be re-opened when higher priority issues are fixed.
