### ISSUE TITLE
Are the steps to provision single-host part of openstack topology

### ISSUE THREAD

**Issue by cmoulliard** [CentOS-PaaS-SIG/linchpin#378]
Hi,

I'm a bit confused as I'm not sure if the steps to provision a single-host are part of openstack topology or not. If this is not the case, then the doc is not up to date as we have the impression to provision openstack single-host

![screenshot 2017-10-16 15 40 29](https://user-images.githubusercontent.com/463790/31615042-8fc38814-b288-11e7-9c9b-9c32cd986d87.png)

Charles

**Comment by herlo** [comment]
I'm not sure why it's laid out like that. It does appear though that section is showing an openstack example provision. We are planning a documentation update for 1.5 (later this year, early next) so watch for the changes to show up at that time.

**Comment by cmoulliard** [comment]
@herlo What is the idea suggested behind steps to provision a "single-host" ? Is it a VM created by openstack ? Is it a VM created using SSH ... ?

**Comment by herlo** [comment]
Fixed by #436
