### ISSUE TITLE
Duplicate topology in documentation

### ISSUE THREAD

**Issue by beerparty** [CentOS-PaaS-SIG/linchpin#386]
In the LinchPin documentation under Example Topologies (https://linchpin.readthedocs.io/en/develop/topologies.html), the item "Beaker Topologies" is listed twice with identical information for both entries.

**Comment by herlo** [comment]
@beerparty thanks! I'll update this soon as I'm planning a review of the documentation very soon now(tm).

**Comment by beerparty** [comment]
I have additional corrections/suggestions for the documentation. What is the preferred method to submit them to you?

**Comment by samvarankashyap** [comment]
@beerparty All the docs are included in docs folder of current repository . 
Feel free to create Pull requests to correct glitches in the documentation.

**Comment by herlo** [comment]
Fixed by #436
