### ISSUE TITLE
libvirt backend fails

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#387]
Hello,

Using the pinfile and topology from: https://github.com/herlo/lp_test_workspace

libvirt fails with the following:

`docker exec -it lp_centos7 /root/linchpin-test.sh
/workdir/Dockerfiles/lp_test_workspace ~
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This
 feature will be removed in a future release. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is 
discouraged. The module documentation details page may explain more about this 
rationale.. This feature will be removed in a future release. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Included file '/usr/lib/python2.7/site-
packages/linchpin/provision/update_aws_cfn_outputs.yml' not found, however since 
this include is not explicitly marked as 'static: yes', we will try and include it 
dynamically later. In the future, this will be an error unless 'static: no' is used 
on the include task. If you do not want missing includes to be considered dynamic, 
use 'static: yes' on the include or set the global ansible.cfg options to make all 
includes static for tasks and/or handlers. This feature will be removed in version 
2.7. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
Action 'up' on Target 'dummy' is complete
	to retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/site.retry
Target 'libvirt': TASK: libvirt : cp img_src to match node name failed with error 'The task includes an option with an undefined variable. The error was: 'img_src' is undefined

The error appears to have been in '/usr/lib/python2.7/site-packages/linchpin/provision/roles/libvirt/tasks/copy_image_src.yml': line 85, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "cp img_src to match node name"
  ^ here

exception type: <class 'ansible.errors.AnsibleUndefinedVariable'>
exception: 'img_src' is undefined'
+ clean_up
+ set +e
+ docker kill lp_centos7
lp_centos7
+ docker rm lp_centos7
lp_centos7
Makefile:12: recipe for target 'test' failed
make: *** [test] Error 2
`

**Comment by herlo** [comment]
@p3ck what is the linchpin command you are using? It should be something like:

`linchpin up <target>`

It looks like you might be trying to run all of the targets in the PinFile?

Also, the issue with libvirt specifically is being address in PR #383, which we're almost done vetting.

**Comment by p3ck** [comment]
Hi Clint,
I modified my command to only issue one target at a time.  Thanks for the suggestion.
But I don't see my particular issue referenced in PR #383 

I can try running my workflow against that PR though...

**Comment by herlo** [comment]
@p3ck I saw the dummy component and then it called libvirt, so I wasn't sure what was going on. Let me know if it continues with the updates from PR #383.

If it continues to fail, would you paste the linchpin command you are running? Additionally, the PinFile and topology would be super helpful.

**Comment by p3ck** [comment]
What makes you think pr383 will fix my issue?

btw - I'm simply running linchpin up libvirt with the pinfile and topology from your repo here: https://github.com/herlo/lp_test_workspace

**Comment by herlo** [comment]
@p3ck specifically, PR #383 rewrites a large portion of the libvirt playbooks. @samvarankashyap has updated the cp_img_src tasks specifically to address the local vs remote copy which is needed for some scenarios. In my testing of PR #383, I ran across this issue as well, and I believe it to be fixed. However, my tests are mostly on my Fedora system. 

I'll spin up a CentOS box and test this soon. Let me know your results if you beat me to it..

**Comment by p3ck** [comment]
as discussed in irc the issue is still present with the latest PR #383

**Comment by p3ck** [comment]
with the latest dependencies installed this isn't a problem anymore.  But I still wonder if we could improve the error reporting to state which dependencies are causing it to fail.
