### ISSUE TITLE
Error / Timeout in beaker provision should cancel the job

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#394]
### Problem Description
The way beaker provisioning currently works presents a problem when the provisioning fails because of timeout when waiting for the resource. The problem is that the submitted beaker job is not canceled, and there is not sufficient information passed to the caller to cancel it manually. 

### Why this is a Problem
- In a test environment where linchpin is called to provision a resource to be used for the test, this results in wasted resources, since restarting the job queues a second job requesting the same resources, making it more likely to fail on a timeout since the first job is already queued.
- Requests that fail in a timeout fashion don't ever supply the job id, since that information is supplied in the *.output file this is not generated. Solving #180 may alleviate this problem in the future; however, even if #180 was fixed, we'd desire a way to ensure that the *beaker job* could be canceled from the command line, hopefully via a linchpin command. 
- Currently, the only command capable of canceling the beaker job is *linchpin destroy*, which expects an inventory file. This file cannot be generated until a machine is reserved by beaker, which itself cannot be guaranteed to occur before the timeout is hit. This means you don't have sufficient information to manually cancel the job on a timeout failure.

### Proposed Solution
Linchpin should cancel the job if it times out. This prevents wasted resources in beaker, and prevents the user from manually having to cancel jobs in beaker via alternative means.

The alternatives I can think of are:
1.  Eliminate the ansible watchdog timeout, so that linchpin only returns when the job is aborted, cancelled, or running.
2. Provide the user the job id of the beaker request even when the provision times out, and a way to monitor the job or cancel it manually via the linchpin cli.

**Comment by seandst** [comment]
I'm looking into at least spitting the URL to the job in the ansible output so it's a little easier to get to beaker from the linchpin call. This should fix #180 and #399, and work to address this. I also think it might be possible to just fulfill this request as-asked, which is to fire off a job cancel request if provisioning times out. I'm keeping this in mind while hacking on #424

**Comment by herlo** [comment]
@seandst #180 has already been fixed here: https://github.com/herlo/linchpin/commit/c3b9163f994111b37db634ce85b60cb3b83c64fe I think it's in the release1.5 branch, but could easily be cherry-picked into the develop branch (for 1.2.x). or the release1.0 branch.

**Comment by jethbu** [comment]
Usage:  rhts-abort -t [JOB|RECIPESET|RECIPE]
https://github.com/beaker-project/rhts/blob/master/bin/rhts-abort

**Comment by jaypoulz** [comment]
I've been working on some logic to accommodate canceling a job in my Jenkins environment, and in doing so I've discovered a related workflow that should be patched with this issue.

Here is a paste bin log of my test failure, starting at the beaker provision step.
http://pastebin.centos.org/535306/

## Problem Workflow
1. The job is running, and linchpin is provisioning from beaker and has reached the step where it submits the job.
2. An interrupt occurs. Perhaps this is caused by a fault on the machine, or perhaps, like my workflow, it is because a user cancels the job.
3. The linchpin run ends without canceling the job.
4. My code notices this, and attempts to do a linchpin teardown on the new resource so that the job is canceled.
5. The teardown fails because the inventory file is missing, so the job is never canceled.
6. The job ends successfully, but with wasted beaker resources still provisioning.

## Solution(s)
If possible, this should be fixed so that the beaker job abort is sent as soon as the ansible-playbook receives the interrupt.

If this isn't possible, the job should at least write out enough information into the generated output/inventory file so that a linchpin teardown can actually tear down the resource.

@herlo Please review this and let me know if you'd prefer that this be tracked in another issue. I believe the first solution is very close to the proposed timeout workflow solution, but if it's not possible to solve this way, it may be simpler to track it in its own space.

**Comment by herlo** [comment]
@jaypoulz Thanks for the comments. To start, the teardown (destroy) doesn't require an inventory file. You probably mean that the teardown doesn't record anything to either the RunDB or resources file.

The trick here is that the 'linchpin destroy' action must know the job id in beaker to destroy it. When 'linchpin up' fails to provision beaker resources, this data is likely not recorded anywhere.  This part could be remedied and provided whether or not a failure occurs. However, I think the solution detailed above is a better option. If the beaker provision fails or times out before reporting data back, linchpin can make another call to cancel the job, and report a failed provision (and exit code).

**Comment by jaypoulz** [comment]
@herlo Thanks for the update. I've fixed my comment accordingly since I don't know the true cause of the teardown failure since it does not require an inventory file, and that is what I would have assumed would cause the issue.
