### ISSUE TITLE
linchpin journal without target fails

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#420]
running linchpin journal without a target will fail even though the help says it should work.

Version: 1.2.0

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [linchpin-dev] linchpin journal should print all targets by default](https://trello.com/c/7k5CWQxg/286-2-linchpin-dev-linchpin-journal-should-print-all-targets-by-default)
