### ISSUE TITLE
RFE: allow inventory file name be specified in layout file

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#421]
A nice feature would be to specify the name of the inventory file in the layout file.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[linchpin-dev] Allow inventory file name be specified in layout file](https://trello.com/c/XI98XVuA/277-linchpin-dev-allow-inventory-file-name-be-specified-in-layout-file)
