### ISSUE TITLE
Allow the uHash value to be optional on resources and inventory output files

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#434]
Per #430, @robled requested to make the uHash be an optional value for both resources and inventories.

Additionally, an update to make the uHash optional would also remove it from inventory filenames. 

NOTE: The uHash value will continue to show up in the database and reporting, but could be safely ignored with these changes.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[linchpin-dev] make uHash optional v1.2.x, v1.5.x](https://trello.com/c/Tq09z1KS/271-linchpin-dev-make-uhash-optional-v12x-v15x)

**Comment by jaypoulz** [comment]
Another enhancement on the flip side of this issue, that may warrant its own issue:
It would be nice if the output of a linchpin run included a way to get the named of the inventory file quickly.

One way to do this would be to print it out at the end of a run. Other ways might be to make it the output of a new command such as `linchpin latest` or even storying the value in an environment variable for reference. Even if it's just the runId, it would be helpful to have a way to construct the name of the generated inventory and output files.

**Comment by herlo** [comment]
@jaypoulz I think this is a good idea, would you mind putting this in as its own issue? I'm happy to work on this feature as I did discuss this with @scoheb as well.
