### ISSUE TITLE
Fresh pip install misses jsonschema dependency

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linchpin#441]
Since December, jsonschema appears to have disappeared from the list of transitive dependencies which Linchpin directly relies upon.

Reproducer:
$ virtualenv testenv
$ . testenv/bin/activate
$ pip install linchpin==1.2.1
$ linchpin up

This will fail during the schema verification step with missing jsonschema.

WORKAROUND:
$ pip install jsonschema==2.6.0

This brings in the dependency and appears to resolve the issue until a permanent fix is released.

**Comment by herlo** [comment]
I've verified this bug and will address it when we target the other features for 1.2.2+. Thanks!
