### ISSUE TITLE
Allow teardown (destroy) based upon data in rundb

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#447]
Per discussions with @jaypoulz  and @scoheb, teardowns using dynamic data require the user to remember the data being passed. To that end, a switch to read the stored data from the RunDB on teardown could be useful.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[linchpin-dev] Provide a flag for doing teardown based upon data in topology or rundb](https://trello.com/c/NTizqbhq/273-linchpin-dev-provide-a-flag-for-doing-teardown-based-upon-data-in-topology-or-rundb)

**Comment by jaypoulz** [comment]
To expand on this, there should be enough information stored in the output and inventory files for the teardown step to work by just specifying the target. It doesn't make sense that you have to pass in template data to teardown, and it makes even less sense that you can pass in template data different than what you passed in to create the environment and teardown will run correctly as long it it compiles.

**Comment by herlo** [comment]
@jaypoulz agreed. This should be the default, as discussed today in the planning meeting. There is still a desire to use the static topology data from PinFile structure, thus others will need a way to disable this feature easily.
