### ISSUE TITLE
Feature Request: variables to grab latest generated runId and inventory path

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#448]
# Overview
This is a feature request to make it easy to grab the latest generated inventory and look up its info in the runDB. It's great to have all of the inventories generated be unique (to prevent thrashing), but currently, you'd have to parse either the run output or the linchpin journal history to be able to quickly grab the last generated inventory file. By giving us environment variables for these, we can now use the environment variables to perform commands on the generated inventory (e.g. running playbooks) and quickly perform a teardown using the runId environment variable.

**Comment by herlo** [comment]
Thanks @jaypoulz for this issue, this comment expands your feature request a little. While using the context in a LinchPin hook is useful, it should also be exported to an environment variable as described above. There may be more than what is listed above, and will be detailed when this feature is investigated.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[linchpin-dev] Add environment variable outputs for easy access outside LinchPin](https://trello.com/c/48GaTnmB/276-linchpin-dev-add-environment-variable-outputs-for-easy-access-outside-linchpin)

**Comment by herlo** [comment]
Per discussions with @jaypoulz, the real goal of this is to get information out of linchpin, including the tx_id, inventory_path, and other bits. This could use the existing context distiller bits, but add an 'all' section with certain fields to extract. 

Additionally, the `linchpin journal --view=tx` could have a `--output=json` (or something similar) which would look up all of the runs in a specific transaction and output the requested fields. By default, only the last record would be shown when using the --output option, but --tx-id would allow lookup of any specific transaction.
