### ISSUE TITLE
Allow external file paths for hooks

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#454]
# Overview
As we discussed in our meeting today, linchpin can potentially supported cinch as a hook by using a symbolic like to point to the cinch playbooks and manually adding the role path to the ansible call.

This is pretty clunky from a user's point of view, and is really only for users with a deep understand of how linchpin is used.

## Short Term Improvement
One way to alleviate some of the clunkiness is to have ansible hooks support both absolute and relative paths. If this were the case, you could just point to the external playbook, and default to add the playbook's location to the path as a reference point for execution. This is how most ansible-playbooks are organized to begin with, and would support a linchpin-cinch workflow nicely.

## Potential Endgame
My goal in asking for this is to allow for linchpin and cinch to work in harmony without being tightly coupled.

I think the best way to do this is for linchpin to support hooks for executables that conform to the ansible-playbook call structure. Currently, cinch does not quite fit that description, but it seems to conform to everything besides the [way it handles inventories](https://github.com/RedHatQE/cinch/issues/209).

Let's say for the sake of argument that the `cinch` and `teardown` commands did follow the ansible-playbook structure completely. If this were true, we could simply extend the existing ansible hook to support 2 further arguments:
1. executable
This would be the name of the executable to call instead of ansible-playbook. In this case, `cinch` or `teardown`.
2. package-name
This is the pip package that the hook needs installed before it can run. If pip doesn't detect that the package is already installed, it would install the package as part of the run.

This would be a sustainable way to extend the ansible-playbook hook in my opinion, because the idea is that you can now support any executable that conforms to ansible-playbook parameters.

**Comment by herlo** [comment]
I'm going to close this one considering that external paths for hooks is doable. I do think we still need a fix for an custom hook that doesn't require writing code into linchpin. I'll create an issue for that separately.
