### ISSUE TITLE
"resources/file.output" no longer available in linchpin workspace

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linchpin#459]
While testing the recent work done for #430, I was able to successfully provision an instance in OpenStack using linchpin in Jenkins as of [this commit](https://github.com/CentOS-PaaS-SIG/linchpin/commit/b11d18b412b1a94c43b915765e7df1f6d2de0106) with our existing linchpin workspaces.  However, the Jenkins teardown step fails, because the resources directory and corresponding output file that we use for the destroy operation is no longer created:

```
[jenkins@jmaster1 openstack-slave]$ find .
.
./PinFile
./credentials
./credentials/cinch.yml
./hooks
./hooks/.gitkeep
./inventories
./inventories/.gitkeep
./inventories/group_vars
./inventories/group_vars/all
./inventories/cinch-test.inventory
./keystore
./keystore/ci-ops-central
./layouts
./layouts/cinch.yml
./topologies
./topologies/cinch.yml
./.rundb
./.rundb/rundb-274973442355001.json
```

Error from Jenkins job workflow:

`15:32:13 ERROR: Failed to copy artifacts from cinch-example-provision with filter: cinch-example/examples/linchpin-topologies/openstack-slave/resources/cinch-test.output`

JJB template that has been using this workflow with linchpin 1.0.4 and prior:

https://github.com/RedHatQE/cinch/blob/master/jjb/ci-jslave-project-sample.yaml#L28

**Comment by herlo** [comment]
Hi @robled can you point me to the code in your cinch project where the resource is used? We could fixup a solution that should work for this situation. It should be fairly trivial.

**Comment by herlo** [comment]
@robled nevermind, I found what I was looking for, thanks.
