### ISSUE TITLE
LinchPin should store beaker_job_id in the RunDB at runtime

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#471]
# Overview
This issue is a follow-up case for when a beaker topology linchpin up could result in wasted beaker resources. After a discussion with @herlo, we've determined that we can fix this by stored the beaker_job_id in RunDB as soon as it becomes available.

## Problem Workflow
1. The Jenkins job is running, and linchpin is provisioning from beaker and has reached the step where it submits the beaker job.
2. An interrupt occurs. Perhaps this is caused by using Control-C on the machine, or perhaps, like my workflow, it is because a user cancels the Jenkins job.
3. The linchpin run ends without canceling the beaker job.
4. My code notices this and attempts to do a linchpin teardown on the new resource so that the job is canceled.
5. The teardown does not cancel the beaker job.

The job ends successfully, but with wasted beaker resources still provisioning.

## Solution
If we store the beaker_job_id in RunDB asap, the teardown call should successfully cancel the beaker job. This will save beaker resources, and result in a clean end state.

**Comment by herlo** [comment]
Thanks @jaypoulz. Per our discussion, it should be pretty simple to add this into the RunDB from the beaker provider immediately after the beaker_job_id value is obtained.

**Comment by herlo** [comment]
To be clear, this actually already happens during the gather_facts role, which occurs after the beaker provisioning role occurs. The problem here is that because an interrupt occurs, LinchPin (and ansible) do not trap this interrupt. However, simply adding the beaker_job_id to the RunDB record should allow for teardown to be successful whether or not the job was interrupted.

**Comment by seandst** [comment]
This makes perfect sense to me, so I'll try to get this on my next sprint.
