### ISSUE TITLE
SPIKE: Create LinchPin External Context

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#486]
# Purpose

As part of the request in https://github.com/CentOS-PaaS-SIG/linchpin/issues/448, I've done some preliminary research, interviews, and brainstorming sessions.

It's become obvious that linchpin needs to provide additional components to make environmental variables available. Additionally, it seems there's a common need for a context to provide data to external resources, be it environment variables, LinchPin hooks, or some other method of exporting the values from within LinchPin after a provisioning/teardown action. As such, this proposal is being presented for comment.

## The LinchPin Context

Currently, there is a concept of a context within LinchPin. It's used to manage all of the variables generated from the linchpin.conf, settings from the CLI shell, incoming environment variables, and various other generated inputs, such as the uhash, inventory_path, etc. This context serves the purpose of also exporting these variables into the extra_vars which are passed when executing the internal playbooks. 

The LinchPin Context is useful internally, but could be useful to external scripts as well. Some of the data provided is sensitive, other data may not be relevant to external scripts. To that end, it may be useful to massage the data to remove this information.

Although it's not likely to be a large part of this discussion, an additional consideration for this context is developers who may create new providers in the future. Knowing what values are available as inputs, and what is required to output to the context will be useful.

## Namespacing

As with many of the variables in Ansible, LinchPin context variables will have a namespace. Currently, this is not the case, but this work will attempt to ensure any context variables will be prepended with 'linchpin_' so as to not conflict with ansible specific variables in the playbooks, or with any other applications which may use similar values in their external application.

## Initial Work

The initial phase is to provide a mechanism for adding and exporting these values from the context. The RunDB is a perfect resource for storing this data as it's already collecting most of it already. Items that are currently not in the RunDB include relevant extra_vars, and inventory data. There may be other data included as more investigation occurs.

Once the data is stored in the RunDB on each run, each variable will be added to the context object. If a variable doesn't have the 'linchpin_' namespace, it will be updated where applicable. The object will then be exported to the requested environment contexts. Currently, those are environment and hooks contexts, but this may be expanded in the future. 

### The Linchpin ID

Currently, LinchPin provides a 'run_id' for each execution of LinchPin. Usually, this is on a target by target basis, and is unique in terms of each target and run_id combination. This is convenient to reuse the data from the previous provision (up) action to teardown (destroy) the same resources. However, it is possible to provision multiple targets at one time. To that end, a new mechanism is warranted to track each invocation.

The Linchpin ID (or linchpin_id) will be provided as a convenience to the external context at the completion of each target. Additionally, the ``--view`` option will be added to the linchpin journal command. The default view will be ``--view=target``. Because LinchPin allows multiple targets in a single execution, the alternate view will be ``--view=exec``, which will list the executions and their results.

### Environment Context Exports

Some considerations need to be made for environmental exports. For instance, using bash as the default (and expected) environment, target names cannot contain a dash (-) or other special characters limited by the POSIX shell requirements. Thus, all environment variables will constrain themselves to UPPERCASE letters, and convert any targets with a dash (-) into an underscore (_). If there's an equal sign (=), this will also fail, and will cause an error at validation of the LinchPin target(s) name.

As part of the export, some values will be a single string, others will be will be in JSON format. The basic difference will be determined based upon need. For instance, an inventory would be in JSON, whereas the run_id will be a string. 

Some of the example variables are listed here.

#### Globals

```
# Represents ID from the 'exec' view (as described above)
LINCHPIN_ID = 2

# Could be useful to know the action performed
LINCHPIN_ACTION = up / destroy / journal? / fetch? / init?

# JSON formatted data from the last execution. 
# FORMAT {LINCHPIN_ID: { ACTION: {target: [run_id, uhash, rc], target: [run_id, uhash, rc]}}}
LINCHPIN_LATEST = '{"2": {"up": {"dummy-new": [187, 77dd, 0], "libvirt-new": [189, 4094, 2]}}}'
```

#### Target Specific

```
LINCHPIN_<TARGET>_<RUNID>_UHASH = 4094
LINCHPIN_<TARGET>_<RUNID>_RC = 2
LINCHPIN_<TARGET>_<RUNID>_INVENTORY_FILE = "/path/to/file.inventory'
```

#### Optional/Expanded

These would be turned on with options in linchpin.conf, or possibly a CLI flag.

```
LINCHPIN_<TARGET>_<RUNID>_EVARS
LINCHPIN_<TARGET>_<RUNID>_PINFILE
LINCHPIN_<TARGET>_<RUNID>_RESOURCES
LINCHPIN_<TARGET>_<RUNID>_INVENTORY
```

(eg. LINCHPIN_LIBVIRT_NEW_189_RESOURCES="{ SOME NUMER OF VALUES }")

NOTE: Some of the above variables could expose credential or sensitive data.

#### Provider Specific DATA

```
LINCHPIN_<TARGET>_<RUNID>_<PROVIDER>_DATA = JSON Formatted Data
```

### LinchPin Journal

As mentioned above, there will be a new functionality added to the linchpin journal. The current workflow is to execute linchpin up or linchpin destroy, then linchpin journal can show the results in the target view.

```
$ linchpin journal dummy-new libvirt-new
    
Target: dummy-new
run_id	    action	     uhash	        rc
------------------------------------------
187    	       up	     77dd	        0
186    	  destroy	     d55e	        0
185    	       up	     d55e	        0

Target: libvirt-new
run_id	    action	     uhash	        rc
------------------------------------------
189    	       up	     4094	        2
188    	  destroy	     3495	        0
187    	       up	     3495	        0
```

A new view will now exist.

```
$ linchpin journal --view=exec
ID: 2
Action: up

target              run_id  uhash       rc
------------------------------------------
dummy-new           187     77dd        0
libvirt-new         189     4094        2
```

### Storing the records in the RunDB

To store the exec records, there already exists a default table, appropriately named 'linchpin'. The format will look like this:

```
        "2": {
            "targets": [
                {
                    "dummy-new": {
                        "187": {
                            "rc": 0,
                            "uhash": "77dd"
                        }
                    },
                    "libvirt-new": {
                        "189": {
                            "rc": 2,
                            "uhash": "4094"
                        }
                    }
                }
            ]
        },
```

It's expected that there will be other features that use this feature in the very near future. Some issues have already been requested, or inspired this work. They are #448, #471, #454, #447, and #479.

**Comment by herlo** [comment]
Whiteboarding / brainstorming a concept for the data that will go into the RunDB, and used for the external context. 

* The ✓ is always included
* The ⏣ indicates the data will be included when the functionality is used (eg. inventory layout)
* The **c** indicates it must be first enabled in the linchpin config before it can be used. 

### Inputs

✓ topology_data
✓layout_data
⏣ hooks_data

### Outputs

✓ resources
 rc (return_code)
⏣ inventory
⏣ inventory_file
c <provider> (provider specific data, eg. "beaker: { bkr_job_ids: [89, 91] }")

### Vars

✓ evars
✓ magics
c user

The 'Vars' field will be new. Additionally, much of what is listed here is not currently in the RunDB and will need to be added.


![linchpin_external_context_rundb](https://user-images.githubusercontent.com/89334/37169201-7aa6bee0-22c4-11e8-99b9-df06737ba044.jpg)

**Comment by herlo** [comment]
# Use Cases

This comment is meant to address common use cases/reasons for having a LinchPin External Context (LEP), and how the having the LEP can benefit users.

## Performing Actions on Provisioned Resources

Likely the most common scenario is a user would like to provision some resources, be given context for these resources to use while acting upon them. A simple example might be to configure docker inside a libvirt vm. The user would provision a resource using linchpin using a simple PinFile:

```
---
libvirt-new:
  topology:
    topology_name: libvirt-new
    resource_groups:
      - resource_group_name: libvirt-new
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: centos71
            uri: qemu:///system
            count: 1
            image_src: file:///var/lib/libvirt/images/CentOS-7-x86_64.qcow2.xz
            memory: 2048
            vcpus: 1
            arch: x86_64
            ssh_key: libvirt
            networks:
              - name: default
            additional_storage: 10G 
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        example-node:
          count: 1
          host_groups:
            - example
```

Executing linchpin, the user would get a context object containing valuable variables.

```
$ linchpin -vvv up
.. snip ..
ID: 24
Action: up

Target              	Run ID	uHash	Exit Code 
-----------------------------------------------------
libvirt-new         	   215	 3f10	        0
```
The context would consist of the following components:

### Environment Variables

Global context variables
```
$ echo $LINCHPIN_ID
24
$ echo $LINCHPIN_LATEST_RUNIDS
24
$ echo LINCHPIN_LATEST
'{"24": {"up": {"libvirt-new": [215, 3f10, 0]}}}'
$ echo $LINCHPIN_LATEST_UHASHES
3f10
$ echo $LINCHPIN_LATEST_RCS
0
```

RunID specific variables
```
$ echo $LINCHPIN_LATEST_TARGETS
libvirt-new
$ echo $LINCHPIN_LIBVIRT_NEW_215_UHASH
3f10
$ echo $LINCHPIN_LIBVIRT_NEW_215_RC
0
$ echo $LINCHPIN_LIBVIRT_NEW_215_INVENTORY_FILE
/path/to/workspace/libvirt-new-3f10.inventory
$ echo $LINCHPIN_LIBVIRT_NEW_215_INVENTORY
{
  "all": [{"192.168.122.114": { "hostname": "192.168.122.114"}}],
  "example": [{"192.168.122.114": { "hostname": "192.168.122.114"}}]
}
```

From this data, a user could now run `ansible-playbook` against the provided inventory. Possibly like so:

```
$ ansible-playbook -i ${LINCHPIN_LIBVIRT_NEW_215_INVENTORY_FILE} site.yml
.. snip ..
```

**Comment by samvarankashyap** [comment]
moving to backlog shall be revisited again
