### ISSUE TITLE
Add needed items to RunDB json and document

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#506]
For #486 and #499 there will be a couple items needed to be added to the RunDB. This data also needs to be documented in at least generalities.

**Comment by herlo** [comment]
Hooks need to be added to inputs. A 'vars' section needs to be available as a pre-work for the External Context (#486).

**Comment by herlo** [comment]
@robnester-rh @flowersncsu, I've completed the first draft of the RunDB documentation. I'm guessing it needs some additional attention. Could you review it and give me feedback in this issue?

http://herlo-linchpin.readthedocs.io/en/context_distiller/advanced/rundb.html

**Comment by herlo** [comment]
@robnester-rh @flowerncsu, I've completed the first draft of the RunDB documentation. I'm guessing it needs some additional attention. Could you review it and give me feedback in this issue?

http://herlo-linchpin.readthedocs.io/en/context_distiller/advanced/rundb.html

**Comment by robnester-rh** [comment]
**From a functional point of view:**
The following statement

> The main constraint to this is that a target called linchpin cannot be used.

Makes me wonder, "why not just name the table something that wouldn't conflict, just to remove the potential for conflict?

**From a documentation point of view:**
I'd say that if you've not implemented something, documenting it is of little use (The user vars section, for example, seems superfluous as any user vars are not currently usable. So, why document them currently.

It's unclear from the documentation what additional items are being added, so I can't really comment further?

**Comment by herlo** [comment]
@robnester-rh To answer your questions. 

I can call the table anything, it's true. But whatever I call the table would not be able to be a target. The data is structured different in the 'linchpin' table. I guess a more obscure table name could work, I just went with what it was called already so as to not do more work. 

As far as the documentation POV, I can see your point. I'll comment that section out until I have further data to add.

Thanks!
