### ISSUE TITLE
linchpin/libvirt unable to deal with generic KVM images that have no cloud-init preinstalled

### ISSUE THREAD

**Issue by dyasny** [CentOS-PaaS-SIG/linchpin#532]
When using the standard KVM images supplied (for example) at https://access.redhat.com/downloads the images have no cloud-init preinstalled. This means linchpin will provision the VMs but without injecting ssh keys, and the VMs will not be accessible for ansible or the user.

For libvirt based installs the workaround would be to inject the keys using libguest tools, like shown here:
https://github.com/redhat-openstack/infrared/blob/09b0042cdfdf48e2d967254cb842f2eb858b9a03/plugins/virsh/tasks/download_images.yml#L31
Of course this means installing libguestfs-tools as well

**Comment by p3ck** [comment]
I think it should try and use virt-customize and if that fails it can fall back to trying cloud-init.
virt-customize will return non-zero if it doesn't recognize the underlying OS (like atomic for example)

**Comment by samvarankashyap** [comment]
@dyasny Could you point out a specific image that you are currently using for the run from 
[https://access.redhat.com/downloads](https://access.redhat.com/downloads)

**Comment by herlo** [comment]
Fixes #610
