### ISSUE TITLE
Allow successfully-provisioned resources to stay provisioned even if others of the same type fail

### ISSUE THREAD

**Issue by flowerncsu** [CentOS-PaaS-SIG/linchpin#538]
It's my understanding, based on some of the conversation around https://github.com/CentOS-PaaS-SIG/linchpin/issues/531 , that successfully provisioned resources will be shut down if others of the same type fail. If this does indeed need to be possible, we would like for it to be an option controlled by a config flag. This behavior isn't an obvious assumption, and so probably should not be the default behavior.

**Comment by samvarankashyap** [comment]
As discussed with @flowerncsu . this can be achieved by manipulating topology defining resource definitions making multiple resource groups.
If not the issue can be reopened again.
