### ISSUE TITLE
Libvirt: Support provisioning on remote hypervisors

### ISSUE THREAD

**Issue by joanbe** [CentOS-PaaS-SIG/linchpin#547]
As a user I would like to use linchpin to deploy virtual machines on a remote hypervisor using the libvirt provider.

**Expected user benefits:**
- Enable testing of complex deployments with multiple machines that would not be possible using the local development machine
- Increased performance and shorter test cycles for end users

**Proposal**
I would like to delegate the following tasks to the remote hypervisor:
- Downloading image (if applicable)
- Local copying of image files
- Network setup
- Virtual machine deployment
- Checking network connectivity of provisioned virtual machines

I would like all linchpin components and generated RunDB data to remain on the local development machine.

**Disussion**
There is already some code that might be used to implement this feature:
- The filter plugin in get_host_from_uri.py could be used to change the uri_hostname parameter (The uri_hostname is used to determine responsibility for downloading and copying of image files).
- The copy_image_src_remote.yml (called from provision_libvirt_node.yml) could possibly be used to handle the downloading and copying of image files on the remote hypervisor.

Currently, setting the `uri` configuration option to `qemu+ssh://<hostname-of-remote-hypervisor>/service` successfully provisions all virtual machine resources except disk source file on the remote hypervisor.

**Comment by herlo** [comment]
Fixed by #586
