### ISSUE TITLE
Logo Proposal for Linchpin

### ISSUE THREAD

**Issue by area55git** [CentOS-PaaS-SIG/linchpin#585]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Linchpin.

I will be pleased to collaborate with you.

**Comment by herlo** [comment]
Hi @area55git this sounds great. Do you have any initial designs you'd like to share? I initially looked into this, but didn't really come up with anything more than an idea. A linchpin usually is an important piece, so maybe using a google images search to start would be helpful? Thanks!

**Comment by herlo** [comment]
https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/README.rst can be a good resource for a summary. The first few lines should suffice. As for colors, something semi-muted, maybe blue and tan or some such come to mind, but there's not definite bias.

**Comment by area55git** [comment]
Hi @herlo, What did you think of the proposal?

**Comment by herlo** [comment]
@area55git I like your work, but I asked for opinions from a few others first. I'm thinking the design might need to change some, but don't know how yet. @samvarankashyap, any thoughts on this logo?

**Comment by samvarankashyap** [comment]
@herlo @area55git : Great work !. It has got a Interesting color gradient. However, the "L" in logo is significant I don't see anything that suggests a "cloud" or just "P" for provisioning tool.  Since, Linchpin is more of a cloud orchestration tool you could as well incorporate cloud symbol into it ( It might be a overkill though ). 
please see: 
1. https://github.com/cloudimmense ( minus gradient color )
Rest said, I like your designs.

**Comment by area55git** [comment]
Hi @samvarankashyap, You like this?

[![LOGO_PROPOSAL_FOR_LINCHPIN_b.jpg](https://s31.postimg.cc/cp27elk63/LOGO_PROPOSAL_FOR_LINCHPIN_b.jpg)](https://postimg.cc/image/wjo90pzdj/)

**Comment by area55git** [comment]
Hi, @herlo, do you like any of the proposals?

**Comment by herlo** [comment]
@area55git Hi, sorry for the slow response.

Personally, the tag line doesn't work for me, but I like the cloud component. I'm leaning toward the blue logo, or a combination of blue and red might be nice. The L in the circle seems unnecessary, but the linchpin logo above was nice. Maybe have the linchpin be inside the circle somehow and not have the 'L', maybe with the cloud instead of a circle? Not sure, just looking for more ideas I think.

Either way, I like the progress of this stuff, and I know it's a process to get right, so thanks for contributing! Let's keep going. :+1:

**Comment by area55git** [comment]
Ok, in 2 or 3 days I will present you another proposal, keep working. 👍

**Comment by area55git** [comment]
Hi @herlo, What do you think of this proposal?

[![LOGO_PROPOSAL_FOR_LINCHPIN_c.jpg](https://s33.postimg.cc/8ivw24vof/LOGO_PROPOSAL_FOR_LINCHPIN_c.jpg)](https://postimg.cc/image/yr70rifrv/)

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_LINCHPIN_c.jpg](https://s33.postimg.cc/4p2fske7z/LOGO_PROPOSAL_FOR_LINCHPIN_c.jpg)](https://postimg.cc/image/l02jovqpn/)

**Comment by herlo** [comment]
@area55git Thank you for these updated logos. I think having the linchpin bits for the logo were better choices. I'm also not keen on the tagline 'Ansible based multicloud orchestrator' in the logo/wordmark. I do like the blue colors in the right-hand cloud logo and the font in the logo above it. Let's keep going forward with more adjustments, if that's ok

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_LINCHPIN_c.jpg](https://s33.postimg.cc/4mrxpq01r/LOGO_PROPOSAL_FOR_LINCHPIN_c.jpg)](https://postimg.cc/image/u5ka2qjln/)

**Comment by area55git** [comment]
what do you think?

**Comment by herlo** [comment]
@area55git I like the logo colors, but don't want a cloud there. Maybe a true linchpin or something closer to that? Maybe a similar to the top one in this link? https://postimg.cc/image/piges181z/ but without the L, and more internal?  I like the idea of something like this: http://www.mirageinc.com/content/images/thumbs/0001239_716-linchpin-with-10-lanyard.jpeg

What do you think @samvarankashyap ?

**Comment by area55git** [comment]
Perfect, I understand, I'm going to present a new proposal

**Comment by area55git** [comment]
Hi @herlo look at this proposal

[![LOGO_PROPOSAL_FOR_LINCHPIN.jpg](https://s33.postimg.cc/bgb6bb0sv/LOGO_PROPOSAL_FOR_LINCHPIN.jpg)](https://postimg.cc/image/d84567k5n/)

**Comment by area55git** [comment]
Hi @herlo

**Comment by herlo** [comment]
@area55git I think the pin itself should be a bit smaller, maybe make it a cotter-type pin (which could be a lower case 'L'). The circle of the linchpin could be a mostly complete circle. I like the tilted linchpin, and would like both a wordmark, logo and image as identifiers of linchpin. I think we're getting there.

Thanks!

**Comment by samvarankashyap** [comment]
@area55git I agree with @herlo  we are almost there !

**Comment by area55git** [comment]
Hi @herlo @samvarankashyap, I'm going to make a new sketch and send it in a few days.

**Comment by samvarankashyap** [comment]
@area55git any update ?

**Comment by samvarankashyap** [comment]
Moving issue to the backlog #1240
