### ISSUE TITLE
doc pages without Title

### ISSUE THREAD

**Issue by alexxa** [CentOS-PaaS-SIG/linchpin#591]
All docs in docs/source/gs have no title, therefore RTD displays those pages as [`Docs >> <no title>`](http://linchpin.readthedocs.io/en/develop/gs/layouts.html), in RTD Search those also displayed as [\<no title\>(from project linchpin)](http://linchpin.readthedocs.io/en/develop/search.html?q=More+detail+about+the+PinFile+can+be+found&check_keywords=yes&area=default). The Firefox and Chrome tabs are also named \<no title\>.

**Comment by herlo** [comment]
@alexxa Thanks for filing this issue! We appreciate the effort.

These docs are intentionally without title as they are to be included in the http://linchpin.readthedocs.io/en/latest/getting_started.html page. Did you find a link on the RTD site that has access to these documents? If not, there is nothing wrong with those documents.

**Comment by alexxa** [comment]
These pages can be open independently. Open for example http://linchpin.readthedocs.io/en/develop/gs/layouts.html  And see <No Title> in the top right corner.

If one searches something and those pages include the result, in Search list it will be linked with <No Title>. See the first result in this search query here: 
http://linchpin.readthedocs.io/en/develop/search.html?q=More+detail+about+the+PinFile+can+be+found&check_keywords=yes&area=default

**Comment by herlo** [comment]
This is true, the can be opened this way. The challenge with this is reuse. These documents can (and often are) reused throughout the documentation. Adding titles would constrain the including documents and would not be contextually correct. I suspect it's possible to have a way to remove the docs from a search as you described.

**Comment by herlo** [comment]
I am curious, however, if you have an idea of how to prevent included documents from being searched? Or something that would help these documents without affecting the including document context?

**Comment by alexxa** [comment]
@herlo 

You include files as:
```
Pinfile                              <-------- Title
--------
.. include:: gs/pinfile.rst
```
I would simply move Title inside of gs/pingfile.rst

**Comment by herlo** [comment]
The problem with moving the title into the file is that sometimes, the files get included more than once, and sometimes, there's more than just a title used before/after including these files. However, I'm creating a Pull Request to remove them from the index.
