### ISSUE TITLE
bad IRC link in docs

### ISSUE THREAD

**Issue by alexxa** [CentOS-PaaS-SIG/linchpin#595]
The current IRC link in docs opens
* "Unable to connect page" in Firefox
* "The site can't be reached" in Chrome

If you replace 
```
`irc.freenode.net <http://irc.freenode.net>`_
        #linchpin IRC chat channel
```
with 
```
`webchat.freenode.net  <https://webchat.freenode.net/?channels=linchpin>`_
        #linchpin chat channel on freenode IRC.
```
It will open a [window](https://webchat.freenode.net/?channels=linchpin), where one needs to specify their nick and hit a Connect button.

Also, I would move the whole "See also" section into a separate file and use `include` as it's used in several places.

Also [Community page](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/community.rst) includes non-existing toc tree.

**Comment by herlo** [comment]
Hi @alexxa, thank you for this report. We should probably have used something like https://freenode.net/changuide to explain what IRC is, and provided the link you gave as an option for using our IRC channel.

If you have time to provide a Pull Request for this, it would be much appreciated.
