### ISSUE TITLE
bkr topology: allow boolean expressions on hostrequire

### ISSUE THREAD

**Issue by wainersm** [CentOS-PaaS-SIG/linchpin#611]
Currently the topology for beaker provision does not allow to pass boolean expressions in hostrequire for selecting the host.

For example, suppose you want to select a host by name like in below Beaker XML:
<or><system><name op='like' value='%gigabyte%'/></system><system><name op='like' value='%thunderx%'/></system><system><name op='like' value='%hawker%'/></system></or>

So I need the ability to pass such as query to hostrequire. It can even be a parameter that you can inject snippets of Beaker XML.

**Comment by herlo** [comment]
Fixed by #614
