### ISSUE TITLE
Update testing framework to use linchpin fetch

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#627]
In conjunction with #626, it is clear that the test framework should be able to use `linchpin fetch` to pull down each of the workspaces for testing. This not only tests the use cases currently in place in linchpin, but also adds verification that the `linchpin fetch` works. 

Ideally, this will also be referenced in the workspace README file.

**Comment by 14rcole** [comment]
Fixed by #1133

**Comment by samvarankashyap** [comment]
Network overloaded due to linchpin fetch. Closing this issue in favor of existing methods
