### ISSUE TITLE
Promote all in one Pinfiles in linchpin init

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#643]
Currently linchpin init uses topology and layout references in the Pinfile generated 
However, In order to avoid confusion for beginners.
Its good to have All in One Pinfile rendered in linchpin init.

**Comment by herlo** [comment]
I have a good idea of how to make this work better. I'm improving linchpin fetch functionality (#644). One of the ideas that has been suggested is to move from a single example workspace, to many example workspaces, which is what this PR does. Additionally, the PR makes it so linchpin can checkout a specific branch, directory, and create a local 'workspaces' structure as opposed to a single workspace.

**Comment by herlo** [comment]
Back in the day, there was a concept around the idea of 'named workspaces'. I think this is still a very viable idea.

This seems to be the direction this is now going so I'll keep doing these little changes as I go along. These changes are also going to be useful for testing going forward in that the test will perform tasks in a simple order.

- `linchpin fetch <workspace>` --name bob
- `linchpin -w bob validate <target>`
- `linchpin -w bob up <target>`
- `linchpin -w bob destroy <target>`

And so on... Eventually, we could do something like:

`linchpin -w git://github.com/herlo/workspaces up -r dummy-example-3 dummy-example-3-target` --name bob

Which would call fetch, and pull down the workspace locally to a temporary directory, go to the dummy-example-3 directory of the checkout, and run `linchpin up` against the PinFile located in there which would have target <dummy-example-3-target> inside. The workspace would then be stored as `bob` in a config file somewhere for future use.

What do you think, @samvarankashyap ?

**Comment by samvarankashyap** [comment]
Sounds good to me !
