### ISSUE TITLE
Document linchpin validate command

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#676]
Now that the linchpin validate command was released with v1.6.1 (#647), it needs documentation.

**Comment by 14rcole** [comment]
The documentation is [here](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/advanced/validator.rst).  Should I move it to match the documentation for the other basic linchpin commands?

**Comment by herlo** [comment]
Ahh, I couldn't see it in the latest documentation. We should probably include it at least [here](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/cli.rst)

**Comment by herlo** [comment]
And if you think it's appropriate, let's add it [here](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/advanced_topics.rst)

**Comment by 14rcole** [comment]
Those are both fine with me

**Comment by herlo** [comment]
@14rcole bumping this so it doesn't get forgotten.
