### ISSUE TITLE
Create documentation for hooks

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#684]
Hooks should be documented on readthedocs.io as a core component. Likely needed to be added to the getting started guide, and have its own section with detailed use cases.

**Comment by wainersm** [comment]
I would really appreciate if we had documentation about hooks, since I've tried to used it and the examples under workspaces are the only references that I have.

**Comment by samvarankashyap** [comment]
@wainersm This will be a task i would be working next.
