### ISSUE TITLE
Move getChangedFile into LinchpinPipelineUtils.groovy

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#693]
In the recent updates to the merge and release process, a new function was introduced in  [JenkinsfileGHPRMerge]https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/config/Dockerfiles/JenkinsfileGHPRMerge#L159). 

It was recommended in PR #685 to move this into LinchpinPipelineUtils.groovy and refactor the getTargetsToTest method also. This ticket is here to track that work.

**Comment by p3ck** [comment]
agreed - it should be moved into the linchpin library.

**Comment by samvarankashyap** [comment]
Closing this issue in favor of #1223
