### ISSUE TITLE
FetchFile missing arguments 

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#698]
When using fetch for local file it fails on:
`unexpected keyword argument 'root_ws'`

For example: `linchpin fetch --protocal local file://my/path`

**Comment by herlo** [comment]
@abraverm was considering removing the 'local' bit from `linchpin fetch`, since essentially, you can just point with `-w` to that location to run `linchpin up`.

Thoughts?

**Comment by abraverm** [comment]
+1

**Comment by herlo** [comment]
@abraverm alright. I'll use this task to track the removal of the local component from `linchpin fetch`.
