### ISSUE TITLE
Fetch protocol detection disabled

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#699]
Linchpin 1.6.2 fetch defaults to git on Click level, in `shell/__init__.py` line 323:
`@click.option('--protocol', 'fetch_protocol', default='git',` 

While older version (1.5.x) detected protocol from URI first, in `cli/__init__.py` line 780- 792:
```
        protocol = fetch_protocol
        if protocol is None:
            self.ctx.log_state('detecting uri type')
            protocol_regex = OrderedDict([
                ('((git|ssh|http(s)?)|(git@[\w\.]+))'
                    '(:(//)?)([\w\.@\:/\-~]+)(\.git)(/)?',
                    'FetchGit'),
                ('^(http|https)://', 'FetchHttp'),
                ('^(file)://', 'FetchLocal')
            ])
            for regex, obj in protocol_regex.items():
                if re.match(regex, src):
                    fetch_protocol = obj
                    break

        if protocol is None:  # assume fetch_protocol is git if None
            protocol = 'FetchGit'

```
I suggest remove `default='git'`

**Comment by herlo** [comment]
@abraverm the problem with removing this is that git can also have 'http(s)' addresses. You must specify the protocol if it's not git. I could alternatively make a configuration option that lets you set the detault?

**Comment by abraverm** [comment]
Then lets remove the outdated code, and I would suggest to support shorter option i.e '-p'

**Comment by herlo** [comment]
@abraverm what code is outdated? If you remove the file bit, I guess it's possible that auto-detection is not necessary. However, if you have a very simple http site, git won't match and there's no problem not passing in `--protocol`.

On the other note `-p` is not available due to the use in the main part of linchpin to support passing in a PinFile which might be named differently. We don't reuse switches. The switch `--proto` could be added, if you like.

**Comment by abraverm** [comment]
the code in cli/__init__.py line 780- 792 is outdated because fetch_protocol always will have value ('git' is default and not None).  

How about '-P'  (capital), but considering there are only two options (web\git) maybe chage it to --scm\--not-scm or --git\--not-git

**Comment by herlo** [comment]
@abraverm actually, what you say about it being outdated is not quite true. If you dig into this [code](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/cli/__init__.py#L780), you can see the regex for git is much more complex than the one for http(s). I do think the big difference though is the `.git` at the end being there.

We could use `--http` as a way to pass the protocol through if it's not git. We don't support every scm though, so having a corresponding `--git` option to be explicit would likely be useful.

**Comment by abraverm** [comment]
But when you call [fetch from cli](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/shell/__init__.py#L323) it will call [lp_fetch with fetch_protocol='git'](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/shell/__init__.py#L344)  and [regex](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/cli/__init__.py#L780) will never be triggered because its not `None`

**Comment by abraverm** [comment]
:smile: 
considerning:
1. file\local will be removed (see #698 )
2. only two other supported options: git vs http
3. '-p' is already used to specify Pinfile

I think the better UX will be git protocol by default ( assuming that's the common case) but allow explicitly with options '--git\--web'. Consequently  the 'auto-detection' should be removed.

**Comment by herlo** [comment]
@abraverm I can live with this option. :smiley:
