### ISSUE TITLE
linchpin does not use keystore_path for creating keys

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#704]
While creating keys in openstack and aws providers linchpin does not use the keystore path variable which ideally should be 
```
workspace/keys
```

Further , There should be a way to configure where the keys are stored in general . Which include the linchpin libvirt key which is currently stored in ~/.config/linchpin

**Comment by herlo** [comment]
@samvarankashyap to add to the comment above. With that keystore_path variable, it could look first in user set locations, but always default to some standard places, like `~/.ssh:<workspace>/keys`.

**Comment by samvarankashyap** [comment]
Linchpin uses default_ssh_key_path from linchpin.conf . Thus, current issue is fixed.
