### ISSUE TITLE
Documentation for OpenShift provider(GCP, oVirt too) for topology schema

### ISSUE THREAD

**Issue by skatlapa** [CentOS-PaaS-SIG/linchpin#708]
Currently, LP doesn't have sufficient documentation for options for openshift_inline. We would need all the required parameters to be documented and the data types defined, just like other providers This is needed for creating openshift provider for H-Dsl.

**Comment by 14rcole** [comment]
@skatlapa @samvarankashyap we now have docs for all three providers.  Does anything need to be added to them in order to consider them complete?

**Comment by samvarankashyap** [comment]
@14rcole Openshift is good. However, gcloud documentation is partial w.r.to credentials example

**Comment by samvarankashyap** [comment]
Fixed with recent updates in the documentation.
