### ISSUE TITLE
linchpin fails to create working directory 

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#718]
linchpin version : 1.6.2 

```
$linchpin -w /tmp/abc  init
Error: [Errno 2] No such file or directory
```
if i do below then it works
```
mkdir /tmp/abc
cd /tmp/abc
linchpin init 
```

**Comment by samvarankashyap** [comment]
@14rcole : 
adding this if condition to the code at 
https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/cli/__init__.py#L209

```
if self.workspace:
            pf_w_path = '{0}/{1}'.format(self.workspace, self.pinfile)
```
solved the issue for me . 
Please let me know if there is a better fix . Since you have already started troubleshooting . 
I hope am not missing any other usecase by adding above `if`

Adding @herlo to conversation

**Comment by samvarankashyap** [comment]
@14rcole sure :) definitely Will submit a PR soon

**Comment by mrniranjan** [comment]
@herlo @samvarankashyap does the patch fix the issue ?, I tested the patch and it failed with same error ?

**Comment by mrniranjan** [comment]
@herlo @samvarankashyap the patch creates the workspace but still throws the error 

```
(linchpin_dir) [root@8fc5ac2a5563 tmp]# /opt/linchpin_dir/bin/linchpin -w /tmp/pnq init
('!!!!pf_w_path !!!!', '/tmp/PinFile')
Error: [Errno 2] No such file or directory
```
i think the pf_w_path should be self.workspace + PinFile ?

**Comment by samvarankashyap** [comment]
@mrniranjan are you sure you are using the develop branch of linchpin ? 
i tried running the same command and I faced no error : 
```
(test_setup) 🎩linchpin -w /tmp/kqz init
PinFile and file structure created at /tmp/kqz
```

**Comment by samvarankashyap** [comment]
@mrniranjan Please try uninstalling linchpin and try again . 
Thanks !
