### ISSUE TITLE
[TESTCASE] - Expand inventory testing

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#723]
Inventory testing needs to be expanded to cover multiple providers with multiple resources requested.  We've been bitten by regressions where the ordering of the topology didn't match the order in the layout file.

May need to create a second dummy provider in order to keep these tests from running too long.

Most likely this will need to be an integration test but could also include unit tests.

**Comment by samvarankashyap** [comment]
@p3ck In addition to that I would suggest the tests to be ran through the nose/unittest framework by making use of linchpin API rather than command line.

**Comment by samvarankashyap** [comment]
fixed by #866
