### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#726]
A developer's guide is needed to help new developers get up to speed. Should cover at least the following:

* Standard workflow 
  * How PRs are tested with Jenkins
  * Reviews and conversations in github
  * Merging to develop
* Style Guide
* API / CLI standards
* Requirements for PRs 
  * integration tests
  * unit tests
  * PEP8 compliance
* Release process

**Comment by p3ck** [comment]
Started this with #995 but looking over the issue I see that I should add some more to it.

**Comment by samvarankashyap** [comment]
One issue pending will be covered with #1116
