### ISSUE TITLE
Add ks_append, kernel_options, and kernel_options_post to Beaker schema

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#731]
Hi guys,

I've been working with some members of QE, and we've hit a use-case where it would be helpful to pass along additional parameters to a Beaker job. This parameters are supported via the CLI, so it should be possible to pass them along just as one would pass along the `ks_meta` parameters.

The additional parameters we had in mind are:
* `ks_append`
* `kernel_options`
* `kernel_options_post`

See the following for additional information on these parameters:
 https://beaker-project.org/docs/man/bkr.html

**Comment by dollierp** [comment]
This issue can probably be closed:
- ks_append has been added in #888 
- kernel_options and kernel_options_post have been added in #889.

**Comment by samvarankashyap** [comment]
closed w.r.to #888 #889
