### ISSUE TITLE
LinchPin Tutorial - SPIKE

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#757]
Create Your Own Adventure Style tutorial

* Introduction (Getting Started)
* Tutorial Landing Page (with a selection of providers, features, etc) for the user to choose.
* Coverage for each Provider and Feature
  * Dummy
  * Openstack
  * AWS
  * Libvirt
  * GCE
  * Beaker
  * Duffy
  * Openshift
  * Ovirt**
  * Rackspace**
  * Inventory Generation
  * Hooks
  * Journal
  * Distiller / External Context / Linchpin Latest

** - If desired as no known demand exists

**Comment by maneeshmehra** [comment]
Remaining work per following JIRA items that were recently scrubbed:

1. Tutorial for Dummy (https://projects.engineering.redhat.com/browse/CONTRA-673)
2. Tutorial for Duffy (https://projects.engineering.redhat.com/browse/CONTRA-672)
3. Tutorial for OpenShift (https://projects.engineering.redhat.com/browse/CONTRA-671)
4. Tutorial for GCE (https://projects.engineering.redhat.com/browse/CONTRA-669)

**Comment by samvarankashyap** [comment]
Few of the video tutorials are added to the linchpin project's GitHub wiki. 
If needed more separate issues can be created.
