### ISSUE TITLE
Add documentation to libvirt provider on how to run linchpin as non root 

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#779]
$subject 
There are no specific instructions or links in linchpin docs on : 
how to setup users for running linchpin as non root user.

**Comment by 14rcole** [comment]
@samvarankashyap does this come down to creating a libvirt group and adding relevant users to it?  I haven't run libvirt as non-root before but I'm happy to take this on if that's the case

**Comment by samvarankashyap** [comment]
@14rcole Yes. Please feel free to take it up .
