### ISSUE TITLE
Add networking support for openstack

### ISSUE THREAD

**Issue by ssegalredhat** [CentOS-PaaS-SIG/linchpin#786]
Currently there is no support to create networks, subnets and routers. We would like to see this added to Linchpin.

**Comment by samvarankashyap** [comment]
@ssegalredhat : Could you be specific about in which providers would you like the above features . 
Would that be just openstack or other providers like aws , gce too.

**Comment by p3ck** [comment]
Break this into separate issues for different providers.  This should be specific to openstack.

**Comment by p3ck** [comment]
testing can be just static network.

**Comment by 14rcole** [comment]
We don't have a way to test the 3 remaining sub-issues here (os_port, os_recordset, and os_zone).  We expect that os_network, os_router, and os_module will cover the vast majority of cases, so I'm going to close this
