### ISSUE TITLE
Disable uhash for specific provider over command line.

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#797]
Currently uhash is enable throughout the topology 
There is a recent request to disable uhash for only certain providers at commandline/conf level. 
forexample : 
If a topology contains aws, openstack, beaker 
user should be able to disable uhash for aws and beaker over commandline/conf 
```
linchpin -vvv up --disable-uhash aws beaker 
```

**Comment by 14rcole** [comment]
It doesn't seem like this is possible.  If I were to provision, for example, [dummy-aws](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/examples/workspaces/dummy-aws/PinFile.dummy-aws.yml), the resources for the dummy host and the aws host would be in the same inventory file.  There's no real way to disable one and not the other.  I believe inventories are broken up by target.  We could have a flag to disable the uhash for a specific target:

```
linchpin -vv up --disable-uhash target1 target1 target2
```

The syntax is a little clunky so we'd probably have to tweak it, but you get the idea

**Comment by samvarankashyap** [comment]
@jaypoulz any thoughts on the above approach ??

**Comment by jaypoulz** [comment]
Seems like the correct approach to me. You could have separate targets for each of your provides, and disable uhash for the targets with the provider you had in question. I think that granularity will work for most use cases.
