### ISSUE TITLE
Tutorial: Add tutorial for linchpin journal exploring all the options

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#864]
$subject
As a part of #757

**Comment by 14rcole** [comment]
There's a journal section of each of the provider-specific tutorials in addition to the more traditional documentation in the commands section.  Given that we have all of that, do we need a separate journal tutorial?

**Comment by samvarankashyap** [comment]
@14rcole I think i missed that. I do not think we need it .
