### ISSUE TITLE
RFE: Quota check

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#871]
Before trying to provision (especially multiple systems), Linchpin should check if the destination has enough quota (hard and soft) to allocate for the run. Hard quota limit should instantly fail, but soft quota limit should allow user options how to handle:
 - greedy wait (timeout x) - provision a system once some quota is released and  its enough
 - total wait (timeout x)- start provisioning only when there is quota for everything
 - fail - don't even try
 - alternatives - try other credentials

**Comment by samvarankashyap** [comment]
For the first 3 cases mentioned in the above issue can be addressed by by pre-up hook before provisioning process is initiated.
However in order to try other credentials the status of one hook needs to be transmitted to other hooks via some channel. Which would be whole another issue to be addressed.

**Comment by samvarankashyap** [comment]
related to  #695 https://github.com/CentOS-PaaS-SIG/linchpin/pull/695

**Comment by 14rcole** [comment]
How would we manage greedy wait with preup hooks?  I understand how fail and total wait would work.  In the case of greedy wait though, we may need to wait in the middle of provisioning.

**Comment by samvarankashyap** [comment]
@14rcole I believe there would not be any wait if the quota check fails in the first place for pre-up case scenario.

**Comment by 14rcole** [comment]
@samvarankashyap you could write a check that waits until the quota is available.  But you could only wait for *all* quota in a preup hook

**Comment by samvarankashyap** [comment]
@14rcole Thought it is possible to wait until the quota clears out. In a scenario where there is a shared account. One might have to wait forever for the quota to clear out. However, We can add a configurable wait time such that the provisioning task can fail after the designated time.

**Comment by abraverm** [comment]
maybe use pre-up, post-up hooks with ignore failure (?) where linchpin will try to provision, if it fails then it will try again and the thing that will make it sane is quota check in the beginning. This is ugly workaround but I think it would work :sweat_smile:

**Comment by 14rcole** [comment]
Wouldn't any sort of quota check introduce a race condition?

**Comment by samvarankashyap** [comment]
@14rcole If the quota check fails , I feel there is no point in waiting for quota to be cleared up because it might take time to clear up resources. quota check can "fail if no resources are available" pre up hook.

**Comment by 14rcole** [comment]
@samvarankashyap but if quota check succeeds, the resources could still be taken by another user in the time it takes linchpin to reserve the machines

**Comment by samvarankashyap** [comment]
It Can be as a part of #857

**Comment by 14rcole** [comment]
Closing due to time constraints as we move into maintenance mode
