### ISSUE TITLE
RFE: SSH to provisioned system

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#873]
Add a command to Linchpin connect to provisioned system `linchpin shell <name>`.
This could be useful for developers and local work with Linchpin.
Implementation example: https://github.com/ansible/ansible/issues/12852#issuecomment-340113272

**Comment by samvarankashyap** [comment]
This feature could be very helpful in troubleshooting the environments that are provisioned.
