### ISSUE TITLE
RFE: Option to trigger hooks manually

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#881]
If hooks fail for some reason then only running the `up` or `destroy` will trigger it again. It will be helpful for development and debugging to have option to trigger hooks, for example:
`linchpin postup --type ansible`

**Comment by samvarankashyap** [comment]
The above request is completely reasonable since linchpin already has rundb in place which stores all the Pinfile details. We can easily access the data and re-run the hooks. There might be some hiccups in determining the workspace and hooks paths which can be addressed easily .

**Comment by 14rcole** [comment]
Can we have some real-world examples of where this would be applicable?

**Comment by abraverm** [comment]
Post hook that triggers ansible playbook. The playbook may fail to multiple reasons and the user would like to run it again for specific target. Command call is defined in Linchpin files and will require the user to build the command manually.

**Comment by p3ck** [comment]
lower priority in relation to API cleanup.

**Comment by samvarankashyap** [comment]
have not started it yet.

**Comment by 14rcole** [comment]
Closing this due to bandwidth constraints as we move into maintenance mode
