### ISSUE TITLE
RFE: Allow hooks to communicate among each other

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#890]
The current implementation of hooks allows them to run independently . However , there needs to be a mechanism to have a communication channel between among them. This request is made in regards to #871 .

**Comment by 14rcole** [comment]
Can you elaborate on the kind of data the hooks would need to share?  This impacts the implementation details

**Comment by samvarankashyap** [comment]
fixed by #1129
