### ISSUE TITLE
Templates do not work

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#919]
Jinja template variables in `docs/source/examples/workspaces/inventory-templates/` are left blank and the template variables for the layout file in `docs/source/examples/workspaces/dummy/PinFile` are treated as string literals so that the inventory file exists inside of a directory called `{{ workspaces }}`

**Comment by skatlapa** [comment]
please make sure you enclose jinja vars in " " and loop me in if needed for next steps, thanks!

**Comment by skatlapa** [comment]
its to do with {raw}, please ignore above (for dummy provider)

**Comment by 14rcole** [comment]
@skatlapa you're right but it still doesn't work.  In the case of the dummy provider, `{% raw %}` is causing the string to be treated as a literal.   Thanks for that tip.  However, the variable values are still not being filled in for whatever reason.  When I remove `{% raw %}, I get a permission denied on `/inventories` because `{{ workspace }}` is empty

**Comment by 14rcole** [comment]
fixed in #925
