### ISSUE TITLE
OKD Provider: Doesn't recognize <provider>.creds, clouds.yaml

### ISSUE THREAD

**Issue by skatlapa** [CentOS-PaaS-SIG/linchpin#921]
Atm, the okd provider doesn't recognize the values passed into provider.creds (same as clouds.yaml for openstack.creds used in HDSL). We see this error[1] when used with default profile with this format[2].

[1] - http://pastebin.test.redhat.com/703337

[2] - http://pastebin.test.redhat.com/703338

**Comment by skatlapa** [comment]
@p3ck @samvarankashyap @14rcole looping in

**Comment by 14rcole** [comment]
what do you get when you run `linchpin validate`?

**Comment by skatlapa** [comment]
Hi, @14rcole I did not run Linchpin Validate, I shall try it and let you know. However, that wouldn't help us much I think here the LP is not honoring openshift.creds for its credential file (unlike openstack provider).

Steps to re-create:
1) Create the credentials as per the format[2] and name the file openshift.creds(or *.creds)
2) Do not specify --creds-path (LP defaults to the environment variable - here is the problem)
3) You'll see the error [1]
[1,2] referenced in the first comment.

I am planning to get back to this on Monday, if you find/solve by then please let me know. Thanks.

**Comment by 14rcole** [comment]
@skatlapa did you try this out with the latest release of linchpin?
