### ISSUE TITLE
OKD: --creds-path if not mentioned the provider defaults to upshift.yml  and does not recognize <provider_file>.creds

### ISSUE THREAD

**Issue by skatlapa** [CentOS-PaaS-SIG/linchpin#929]
OKD: --creds-path if not mentioned the provider defaults to upshift.yml and does not recognize <provider_file>.creds

We need to have a way to not pass --creds-path and be using openshift.creds, just like OpenStack provider.
It was previously raised as: #770

**Comment by skatlapa** [comment]
OKD: --creds-path if not mentioned the provider defaults to upshift.yml and does not recognize <provider_file>.creds

We need to have a way to not pass --creds-path and be using openshift.creds, just like OpenStack provider. 
It was previously raised as: https://github.com/CentOS-PaaS-SIG/linchpin/issues/770

**Comment by samvarankashyap** [comment]
fixed by #973
