### ISSUE TITLE
Linchpin to support provisioning of VMware VMs 

### ISSUE THREAD

**Issue by ohochman** [CentOS-PaaS-SIG/linchpin#990]
**Is your feature request related to a problem? Please describe.**

In order to use Linchpin as a cross-team solution: OSP, OCP, CNV, Rhhi.next -  we should have Linchpin to support the provision for all the different teams virtualization platforms.  
VMware is currently missing for the CNV team.  

**Describe the solution you'd like**
VMware provisioning support.

**Comment by samvarankashyap** [comment]
@ohochman: What would be the minimum requirements to be supported in linchpin ?
like vm, network , storage, floating ip ?

**Comment by RazTamir** [comment]
> @ohochman: What would be the minimum requirements to be supported in linchpin ?
> like vm, network , storage, floating ip ?

Hi @samvarankashyap, 
We'll need the same supported requirements we have for AWS or Libvirt with Linchpin.

**Comment by samvarankashyap** [comment]
fixed by #1084
